import {glossaryParts,historyTimeline} from './guide.js';
import {defaultTripId,orderedTrips,todayDay,dayNumber,dayTitle} from './navigation.js';
import {guidesForTrip,researchedAt as customsResearchedAt} from './customs.js';
import {config} from './config.js';
import * as cloud from './firebase.js';
import * as store from './storage.js';
import {parseImport,normalizeTrip,tripMeta,attractions,uid,dateLabel,sizeLabel,MAX_FILE,text,normalizeMeta} from './model.js';
import {downloadTrip,deleteDownload,removeOrphans} from './offline.js';
const $=id=>document.getElementById(id), main=$('main');
const state={user:null,entries:new Map(),downloads:new Map(),outbox:new Map(),selectedId:null,selectionExplicit:false,status:'Starting…',epoch:0,loaded:false};
let unsubscribe, syncJob, syncAgain=false, routeKey='', viewToken=0, importTrips=[], noticeTimer, photoList=[], photoIndex=0, busyImport=false;
const scrolls=new Map(), downloadsRunning=new Map(), customsCountries=new Map(),deletesRunning=new Set();
let selectorSignature='',initialTripId=route().id;
const icons={book:'M4 4h6l2 2 2-2h6v16h-6l-2 2-2-2H4zM12 6v16',back:'m14 5-7 7 7 7',arrow:'m9 5 7 7-7 7',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',photo:'M3 3h18v18H3zM3 17l6-6 5 5 3-3 4 4M8 7h.01'};
function h(tag,props={},...children){const e=document.createElement(tag);for(const [k,v] of Object.entries(props)){if(v==null)continue;if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='disabled')e.disabled=v;else e.setAttribute(k,String(v));}for(const c of children.flat(Infinity))if(c!=null)e.append(c instanceof Node?c:document.createTextNode(String(c)));return e;}
function icon(name){const e=document.createElementNS('http://www.w3.org/2000/svg','svg');e.setAttribute('viewBox','0 0 24 24');e.setAttribute('aria-hidden','true');const p=document.createElementNS(e.namespaceURI,'path');p.setAttribute('d',icons[name]||icons.book);e.append(p);return e;}
function button(label,fn,primary=false){return h('button',{type:'button',class:`button ${primary?'primary':''}`,onclick:fn},label);}
function link(label,href,props={}){return h('a',{href,...props},label);}
function external(label,href){return link(label,href,{target:'_blank',rel:'noopener noreferrer'});}
function guideText(trip,value){return glossaryParts(value,trip.glossary).map(part=>part.term?h('button',{type:'button',class:'glossary-word','aria-haspopup':'dialog','aria-controls':'glossaryDialog',onclick:()=>{$('glossaryTitle').textContent=part.term.term;$('glossaryDefinition').textContent=part.term.definition;showDialog($('glossaryDialog'));}},part.text):part.text);}
function guideParagraph(trip,value,props={}){return h('p',props,guideText(trip,value));}
function image(src,alt,cls=''){if(!src)return h('div',{class:`placeholder ${cls}`},icon('photo'));const img=h('img',{src,alt,loading:'lazy',decoding:'async',class:cls});img.addEventListener('error',()=>{img.replaceWith(h('div',{class:`placeholder ${cls}`,'aria-label':`${alt || 'Image'} unavailable`},icon('photo')));},{once:true});return img;}
function notice(message){$('notice').textContent=message;$('notice').classList.remove('hidden');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').classList.add('hidden'),6500);}
function status(message){state.status=message;$('connection').textContent=message;const text=$('syncStatus');if(text)text.textContent=message;}
function route(){const parts=(location.hash.slice(1)||'/trip').split('/').filter(Boolean);return {kind:parts[0]||'trip',id:parts[1],day:parts[2],attraction:parts[3]};}
const tripHref=id=>`#/trip/${id}`,dayHref=(id,day)=>`#/day/${id}/${day}`,attrHref=(id,day,a)=>`#/attraction/${id}/${day}/${a}`;
function back(label,href){return link([icon('back'),label],href,{class:'back-link'});}
function empty(title,message,action){return h('div',{class:'empty'},icon('book'),h('h1',{},title),h('p',{},message),action);}
function selectDefault(){if(!state.entries.has(state.selectedId))state.selectedId=defaultTripId(state.entries.values());}
function refreshSelector(){
 selectDefault();const select=$('tripSelect');$('tripSelector').classList.toggle('hidden',!state.user);
 const entries=orderedTrips(state.entries.values());const signature=JSON.stringify(entries.map(e=>[e.id,e.meta.name,e.meta.startDate,e.meta.endDate,e.archived]));
 if(signature!==selectorSignature){selectorSignature=signature;select.replaceChildren();
  if(!entries.length)select.append(h('option',{value:''},'No trips yet'));
  for(const archived of [false,true]){const group=h('optgroup',{label:archived?'Archived':'Trips'});for(const e of entries.filter(e=>e.archived===archived))group.append(h('option',{value:e.id},`${e.meta.name}${e.archived?' (archived)':''}`));if(group.children.length)select.append(group);}
 }
 select.disabled=!entries.length;select.value=state.selectedId||'';
 document.querySelector('[data-tab=trip]').href=state.selectedId?tripHref(state.selectedId):'#/trip';
 document.querySelector('[data-tab=customs]').href=state.selectedId?`#/customs/${state.selectedId}`:'#/customs';refreshToday();
}
function refreshToday(){const day=state.user?todayDay(state.entries.get(state.selectedId)):null;const banner=$('todayShortcut');banner.classList.toggle('hidden',!day);document.body.classList.toggle('has-today-shortcut',Boolean(day));if(day){banner.href=dayHref(state.selectedId,day.id);banner.replaceChildren(h('span',{},h('strong',{},'Today'),h('span',{},dayTitle(state.entries.get(state.selectedId).meta,day))),icon('arrow'));}}
function updateNav(){const kind=route().kind;const tab=kind==='settings'?'settings':kind==='customs'?'customs':'trip';document.body.classList.toggle('trips-view',tab!=='settings');document.querySelectorAll('[data-tab]').forEach(a=>{const active=a.dataset.tab===tab;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});refreshSelector();}
$('tripSelect').addEventListener('change',()=>{const id=$('tripSelect').value;if(!state.entries.has(id))return;state.selectedId=id;state.selectionExplicit=true;const kind=route().kind;scrolls.clear();if(kind==='settings'){updateNav();renderSettings();window.scrollTo(0,0);}else location.hash=kind==='customs'?`/customs/${id}`:tripHref(id).slice(1);});
let midnightTimer;
function scheduleToday(){clearTimeout(midnightTimer);refreshToday();const now=new Date(),next=new Date(now);next.setHours(24,0,0,50);midnightTimer=setTimeout(scheduleToday,next-now);}
window.addEventListener('focus',scheduleToday);document.addEventListener('visibilitychange',()=>{if(!document.hidden)scheduleToday();});
const tabBar=document.querySelector('.main-nav');new ResizeObserver(()=>document.documentElement.style.setProperty('--tabbar-height',`${tabBar.getBoundingClientRect().height}px`)).observe(tabBar);
function gate(){updateNav();main.replaceChildren(h('section',{class:'panel auth-card'},h('a',{class:'brand',href:'#/trips'},icon('book'),'Glauco'),h('h1',{},'A guide for every stop.'),h('p',{},'Stories, details, and things to notice. Your personal guidebook, ready to take along.'),cloud.configured()?button('Sign in with Google',signIn,true):h('p',{},'Connect your Firebase project to get started.'),h('p',{class:'small',id:'gateMessage'},state.status),link(cloud.configured()?'Setup & import guide':'Set up Glauco','setup.html',{class:'setup-link'})));}
async function signIn(){if(!cloud.configured())return;try{await cloud.login();}catch(error){status(error.code==='auth/popup-blocked'?'Allow the Google sign-in popup, then try again.':`Sign-in did not finish (${error.code||'connection error'}). Check Firebase setup.`);gate();}}
async function ask(title,message,confirmLabel='Continue'){$('confirmTitle').textContent=title;$('confirmText').textContent=message;$('confirmDialog').querySelector('button[value=confirm]').textContent=confirmLabel;return new Promise(resolve=>{const dialog=$('confirmDialog');dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true});showDialog(dialog);});}
function showDialog(dialog){dialog.returnValue='';history.pushState({...history.state,glaucoDialog:dialog.id},'',location.href);dialog.showModal();}
for(const dialog of document.querySelectorAll('dialog')){
 dialog.addEventListener('click',event=>{if(event.target===dialog && !(dialog.id==='importDialog'&&busyImport))dialog.close('cancel');});
 dialog.addEventListener('cancel',event=>{if(dialog.id==='importDialog'&&busyImport)event.preventDefault();});
 dialog.addEventListener('close',()=>{if(history.state?.glaucoDialog===dialog.id)history.back();});
}
window.addEventListener('popstate',()=>{document.querySelectorAll('dialog[open]').forEach(d=>{if(history.state?.glaucoDialog!==d.id)d.close('cancel');});});
window.addEventListener('hashchange',()=>{const newKey=location.hash||'#/trip';if(newKey===routeKey)return;scrolls.set(routeKey,window.scrollY);routeKey=newKey;renderRoute();requestAnimationFrame(()=>window.scrollTo(0,scrolls.get(routeKey)||0));});
function downloadStatus(entry){const d=state.downloads.get(entry.id);if(!d)return h('span',{class:'status'},state.outbox.has(entry.id)?'Waiting to sync':'Not downloaded');const ready=d.revision===entry.revision;return h('span',{class:`status ${ready?'ready':'warning'}`},`${ready?'✓ Offline ready':'Download update available'} · ${sizeLabel(d.bytes)}`);}
function patchTrips(){const previous=state.selectedId;refreshSelector();if(previous!==state.selectedId||route().kind==='trips'||(route().kind==='trip'&&!route().id))renderRoute();else if(route().kind==='settings')renderSettings();}
function titleBlock(title,subtitle,action){return h('div',{class:'page-heading'},h('div',{},h('h1',{},title),h('p',{class:'muted'},subtitle)),action);}
function visibleEntry(id){return state.entries.get(id);}
async function ensureTrip(entry){if(!navigator.onLine){const d=state.downloads.get(entry.id);if(d)return d.trip;if(state.outbox.has(entry.id)&&entry.trip)return entry.trip;throw new Error('Download this trip while online to read it without a connection.');}if(entry.trip)return entry.trip;const epoch=state.epoch,revision=entry.revision;const trip=await cloud.readRemote({...entry.meta,revision});if(epoch!==state.epoch||!state.user||state.entries.get(entry.id)?.revision!==revision)throw new Error('The trip changed. Open it again.');entry.trip=trip;return trip;}
async function renderRoute(){
 const token=++viewToken;let r=route();const keepComparisons=main.firstElementChild?.dataset.articleKey===`${r.id}/${r.day}/${r.attraction}`&&$('comparisonsTab')?.getAttribute('aria-selected')==='true';
 if(state.user){if(r.id&&state.entries.has(r.id)){state.selectedId=r.id;}selectDefault();
  if(!['settings','customs','trip','day','attraction'].includes(r.kind)||((r.kind!=='settings')&&state.selectedId&&r.id!==state.selectedId)){
   const href=r.kind==='customs'?`#/customs/${state.selectedId}`:state.selectedId?tripHref(state.selectedId):'#/trip';history.replaceState(null,'',href);routeKey=href;r=route();
  }
 }
 updateNav();if(!state.user)return gate();if(r.kind==='settings')return renderSettings();
 const entry=visibleEntry(state.selectedId);
 if(!entry){main.replaceChildren(empty('Your next trip starts here.','Import a Glauco trip file in Settings to open your guidebook.',link('Open Settings','#/settings',{class:'button primary'})));return;}
 let trip;
 try{if(!entry.trip&&navigator.onLine)main.replaceChildren(empty('Opening your trip…','Loading its guidebook.'));trip=await ensureTrip(entry);}catch(error){if(token===viewToken)main.replaceChildren(empty('This trip needs a connection.',error.message,navigator.onLine?button('Try again',renderRoute):link('Manage downloads','#/settings')));return;}
 if(token!==viewToken)return;
 if(r.kind==='customs')renderCustoms(entry,trip);
 else if(r.kind==='trip')renderTrip(entry,trip);
 else {const day=trip.days.find(d=>d.id===r.day);if(!day){main.replaceChildren(back('Trip',tripHref(entry.id)),empty('Day not found','Choose another day from the trip.'));return;}if(r.kind==='day')renderDay(entry,day);else{const a=day.attractions.find(a=>a.id===r.attraction);if(a)renderAttraction(entry,trip,day,a,keepComparisons);else main.replaceChildren(back('Day',dayHref(entry.id,day.id)),empty('Attraction not found','Choose another attraction from this day.'));}}
 main.focus({preventScroll:true});
}
function renderCustoms(entry,trip){
 const glossary=(trip.glossary||[]).length?h('section',{class:'panel trip-glossary'},h('h2',{},'Key terms for this trip'),h('dl',{},...trip.glossary.map(g=>h('div',{class:'glossary-term'},h('dt',{},g.term),h('dd',{},g.definition))))):null;
 const guides=guidesForTrip(trip);if(!guides.length){main.replaceChildren(glossary,empty('A local guide is not available yet.','Customs guides currently cover Cambodia and Thailand. Your trip’s attractions remain available in Trip.'));return;}
 const selected=guides.find(g=>g.id===customsCountries.get(entry.id))||guides[0];
 const countries=h('div',{class:'segmented country-tabs','aria-label':'Country'},...guides.map(g=>h('button',{type:'button',class:g===selected?'active':'','aria-pressed':g===selected,onclick:()=>{customsCountries.set(entry.id,g.id);renderCustoms(entry,trip);}},g.name)));
 const article=h('article',{class:'customs-guide'},h('h2',{},selected.name),h('p',{class:'muted'},selected.intro),...selected.sections.map(s=>h('section',{class:'panel guide-text'},h('h2',{},s.heading),...s.paragraphs.map(p=>guideParagraph(trip,p)))));
 article.append(h('section',{class:'panel phrase-guide'},h('h2',{},`Useful ${selected.language}`),h('p',{class:'small'},selected.phraseNote),h('dl',{class:'phrase-list'},...selected.phrases.map(([meaning,native,sound])=>h('div',{class:'phrase'},h('dt',{},meaning),h('dd',{},h('span',{class:'native-phrase',lang:selected.lang},native),h('span',{class:'phrase-sound'},sound)))))));
 article.append(h('section',{class:'sources'},h('h2',{},'Sources and further reading'),h('p',{class:'small'},`Checked ${dateLabel(customsResearchedAt)}. Transport options and venue guidance can change. The suggestions marked as ours are practical planning advice.`),h('ul',{},...selected.sources.map(([title,url])=>h('li',{},external(title,url))))));
 main.replaceChildren(glossary,guides.length>1?countries:null,article);
}
function renderTrip(entry,trip){const search=h('input',{id:'tripSearch',type:'search',placeholder:'Search this trip','aria-label':'Search this trip',maxlength:150});const clear=h('button',{type:'button',class:'hidden','aria-label':'Clear search',onclick:()=>{search.value='';search.focus();updateSearch();}},'×');const days=h('div',{id:'days',class:'days'},...trip.days.map(d=>{
 const heading=link([h('div',{},h('h2',{},dayTitle(trip,d)),h('p',{},dateLabel(d.date,{weekday:'long',month:'long',day:'numeric'}))),icon('arrow')],dayHref(entry.id,d.id),{class:'day-heading'});
 const strip=h('div',{class:'thumb-strip','aria-label':`Attractions on ${dateLabel(d.date)}`},...d.attractions.map(a=>link(image(a.photos[0]?.thumbnailUrl||a.photos[0]?.url,'',a.photos.length?'':'placeholder'),attrHref(entry.id,d.id,a.id),{class:`thumbnail ${a.photos.length?'':'placeholder'}`,'aria-label':a.name,title:a.name})));
 const card=h('article',{class:'day-card',onclick:event=>{if(!event.target.closest('a,button')&&!event.target.closest('.thumb-strip')&& !window.getSelection()?.toString())location.hash=dayHref(entry.id,d.id).slice(1);}},heading,strip);return card;
 }));const results=h('div',{id:'searchResults',class:'hidden','aria-live':'polite'});
 main.replaceChildren(h('div',{class:'search-wrap'},icon('search'),search,clear),results,days);
 if(!navigator.onLine){main.insertBefore(h('p',{class:'offline-note'},state.downloads.get(entry.id)?.revision===entry.revision?'Reading your downloaded guide offline.':'Reading the saved version of this trip. Reconnect to check for updates.'),days);}
 const searchable=attractions(trip).map(item=>({...item,text:[item.attraction.name,item.attraction.location,...item.attraction.summary,...(item.attraction.notice||[]),...(item.attraction.comparisons||[]).flatMap(c=>c.paragraphs),...(item.attraction.originality||[]),...(item.attraction.history||[]).flatMap(event=>[event.label,event.title,event.text]),...item.attraction.facts.flatMap(f=>[f.label,f.value]),...item.attraction.sections.flatMap(s=>[s.heading,...s.paragraphs])].join(' ').toLocaleLowerCase()}));
 function updateSearch(){clear.classList.toggle('hidden',!search.value.length);const query=search.value.trim().toLocaleLowerCase();days.classList.toggle('hidden',Boolean(query));results.classList.toggle('hidden',!query);if(!query){results.replaceChildren();return;}const matches=searchable.filter(a=>a.text.includes(query));results.replaceChildren(h('p',{class:'small'},`${matches.length} ${matches.length===1?'attraction':'attractions'} found`),...matches.map(({day,attraction:a})=>link([image(a.photos[0]?.thumbnailUrl,'',''),h('div',{},h('h3',{},a.name),h('p',{},`${dateLabel(day.date)} · ${dayTitle(trip,day)}`))],attrHref(entry.id,day.id,a.id),{class:'result'})));}
 search.addEventListener('input',updateSearch);
}
function renderDay(entry,day){main.replaceChildren(back(entry.meta.name,tripHref(entry.id)),titleBlock(dayTitle(entry.meta,day),dateLabel(day.date,{weekday:'long',month:'long',day:'numeric',year:'numeric'})),h('div',{class:'attraction-grid'},...day.attractions.map(a=>h('article',{class:'attraction-card'},link([image(a.photos[0]?.url,'',a.photos.length?'':'placeholder'),h('div',{class:'attraction-body'},h('h2',{},a.name),h('p',{},a.visitTime||a.location))],attrHref(entry.id,day.id,a.id),{class:'attraction-link'})))));}
function renderAttraction(entry,trip,day,a,keepComparisons=false){const articleKey=`${entry.id}/${day.id}/${a.id}`;const article=h('article',{class:'article','data-article-key':articleKey},back(`Day ${dayNumber(trip,day.id)}`,dayHref(entry.id,day.id)),h('p',{class:'eyebrow'},dateLabel(day.date,{month:'short',day:'numeric'})+(a.visitTime?` · ${a.visitTime}`:'')),h('h1',{},a.name),a.location?h('p',{class:'article-location'},a.location):null);
 if(a.photos.length)article.append(h('div',{class:'photo-gallery','aria-label':'Attraction photos'},...a.photos.map((p,index)=>h('button',{class:'photo-tile',type:'button','aria-label':`View photo ${index+1} of ${a.name}`,onclick:()=>{photoList=a.photos.map(photo=>({...photo,alt:a.name}));photoIndex=index;showPhoto();showDialog($('photoDialog'));}},image(p.url,a.name)))));
 const details=h('section',{id:'attractionDetails',role:'tabpanel','aria-labelledby':'detailsTab'});
 if(a.facts.length)details.append(h('dl',{class:'facts'},...a.facts.map(f=>h('div',{class:'fact'},h('dt',{},f.label),h('dd',{},guideText(trip,f.value))))));
 if(a.notice?.length)details.append(h('section',{class:'notice-checklist'},h('h2',{},'Three things to notice'),h('ul',{},...a.notice.map(item=>h('li',{},h('span',{'aria-hidden':'true'},'✓'),h('span',{},guideText(trip,item)))))));
 details.append(h('section',{class:'guide-text','aria-label':'Quick summary'},h('h2',{},'At a glance'),...a.summary.map(p=>guideParagraph(trip,p))));
 const timeline=historyTimeline(trip,a.id);if(timeline.length)details.append(h('section',{class:'history-section guide-text'},h('h2',{},'History timeline'),timeline.some(event=>!event.current)?h('p',{class:'small'},'This site alongside earlier places discussed in Comparisons.'):null,h('ol',{class:'history-timeline'},...timeline.map(event=>h('li',{class:event.current?'history-event current':'history-event'},h('span',{class:'history-date'},event.label),h('div',{},event.current?h('span',{class:'history-site'},a.name):link(event.attraction.name,attrHref(entry.id,event.day.id,event.attraction.id),{class:'history-site'}),h('h3',{},event.title),event.text?guideParagraph(trip,event.text):null))))));
 if(a.originality?.length)details.append(h('section',{class:'originality-section guide-text'},h('h2',{},'What’s original?'),...a.originality.map(p=>guideParagraph(trip,p))));
 if(a.sections.length){const moreDetails=h('section',{id:'moreDetail',class:'guide-text hidden'},...a.sections.map(s=>h('section',{},h('h2',{},s.heading),...s.paragraphs.map(p=>guideParagraph(trip,p)))));const more=h('button',{type:'button',class:'button read-more','aria-expanded':'false','aria-controls':'moreDetail',onclick:()=>{const open=moreDetails.classList.contains('hidden');moreDetails.classList.toggle('hidden',!open);more.setAttribute('aria-expanded',String(open));more.textContent=open?'Show less':'Read more';}},'Read more');details.append(more,moreDetails);}
 const sources=h('section',{class:'sources'},h('h2',{},'Further reading'));if(a.wikipediaUrl)sources.append(external('Read on Wikipedia ↗',a.wikipediaUrl));if(a.sources.length)sources.append(h('ul',{},...a.sources.map(s=>h('li',{},external(s.title,s.url)))));if(a.researchedAt)sources.append(h('p',{class:'small'},`Researched ${dateLabel(a.researchedAt)}. Practical details may change.`));
 details.append(sources);
 const all=attractions(trip),index=all.findIndex(item=>item.attraction.id===a.id);
 const comparisons=h('section',{id:'attractionComparisons',class:'hidden',role:'tabpanel','aria-labelledby':'comparisonsTab'});
 const validComparisons=(a.comparisons||[]).map(c=>({...c,target:all.slice(0,index).find(item=>item.attraction.id===c.attractionId)})).filter(c=>c.target);
 comparisons.append(h('p',{class:'small comparison-intro'},'Connections to places earlier in your itinerary.'));
 if(validComparisons.length)comparisons.append(...validComparisons.map(c=>h('section',{class:'panel guide-text comparison'},h('h2',{},`Compared with ${c.target.attraction.name}`),h('p',{class:'small'},dateLabel(c.target.day.date)),...c.paragraphs.map(p=>guideParagraph(trip,p)),link(`Revisit ${c.target.attraction.name}`,attrHref(entry.id,c.target.day.id,c.target.attraction.id)))));

 const tabs=h('div',{class:'segmented attraction-tabs',role:'tablist','aria-label':'Attraction information'});
 function activateTab(kind){for(const tab of tabs.children){const active=tab.id===`${kind}Tab`;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;}details.classList.toggle('hidden',kind!=='details');comparisons.classList.toggle('hidden',kind!=='comparisons');}
 for(const [kind,label,panel] of [['details','Details','attractionDetails'],['comparisons','Comparisons','attractionComparisons']])tabs.append(h('button',{id:`${kind}Tab`,type:'button',role:'tab','aria-controls':panel,'aria-selected':kind==='details',tabindex:kind==='details'?0:-1,class:kind==='details'?'active':'',onclick:()=>activateTab(kind)},label));
 tabs.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?tabs.firstChild:event.key==='End'?tabs.lastChild:event.target===tabs.firstChild?tabs.lastChild:tabs.firstChild;next.click();next.focus();}});
 if(validComparisons.length){if(keepComparisons)activateTab('comparisons');article.append(tabs,details,comparisons);}else{details.removeAttribute('role');details.removeAttribute('aria-labelledby');article.append(details);}
 const nav=h('nav',{class:'article-navigation','aria-label':'Attraction navigation'});if(index>0){const p=all[index-1];nav.append(link(`← ${p.attraction.name}`,attrHref(entry.id,p.day.id,p.attraction.id),{class:'button ghost'}));}if(index<all.length-1){const n=all[index+1];nav.append(link(`${n.attraction.name} →`,attrHref(entry.id,n.day.id,n.attraction.id),{class:'button ghost'}));}article.append(nav);main.replaceChildren(article);}
function showPhoto(){const p=photoList[photoIndex];$('largePhoto').src=p.url;$('largePhoto').alt=p.alt||`Photo ${photoIndex+1}`;$('photoNavigation').classList.toggle('hidden',photoList.length<2);$('photoDialog').querySelector('.photo-stage').scrollTop=0;$('previousPhoto').disabled=photoList.length<2;$('nextPhoto').disabled=photoList.length<2;}
function stepPhoto(n){photoIndex=(photoIndex+n+photoList.length)%photoList.length;showPhoto();}
$('previousPhoto').onclick=()=>stepPhoto(-1);$('nextPhoto').onclick=()=>stepPhoto(1);$('closePhoto').onclick=()=>$('photoDialog').close();
let touchStart; $('photoDialog').addEventListener('touchstart',e=>{touchStart={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};},{passive:true});$('photoDialog').addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)stepPhoto(dx>0?-1:1);touchStart=null;},{passive:true});document.addEventListener('keydown',e=>{if($('photoDialog').open && ['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();stepPhoto(e.key==='ArrowLeft'?-1:1);}});
function renderSettings(){const theme=document.documentElement.dataset.theme||'dark';const style=document.documentElement.dataset.style||'classic';const appearance=h('section',{class:'panel'},h('h2',{},'Appearance'),h('p',{},'Choose the look that feels best wherever you are.'),h('h3',{},'Style'),h('div',{class:'toolbar'},...[['classic','Classic'],['explorer','Explorer']].map(([s,label])=>h('button',{type:'button',class:`button ${s===style?'primary':''}`,'aria-pressed':s===style,onclick:()=>{applyStyle(s);renderSettings();}},label))),h('p',{class:'small'},style==='explorer'?'A parchment field journal. Light and dark apply to the Classic style.':'The standard Glauco look.'),h('h3',{},'Colors'),h('div',{class:'toolbar'},...['light','dark'].map(t=>h('button',{type:'button',class:`button ${t===theme?'primary':''}`,'aria-pressed':t===theme,disabled:style==='explorer',onclick:()=>{applyTheme(t);renderSettings();}},t==='light'?'Light':'Dark'))));const account=h('section',{class:'panel'},h('h2',{},'Account'),h('p',{},state.user.email||'Signed in with Google'),h('p',{class:'small',id:'syncStatus'},state.status),button('Sign out',signOut));const downloads=h('section',{class:'panel full'},h('h2',{},'Offline downloads'),h('p',{},'Downloads are saved on this device. Removing one keeps the trip in your shared collection.'),h('div',{id:'downloadList'}));const imports=h('section',{class:'panel'},h('h2',{},'Import a guidebook'),h('p',{},'Use a Glauco trip file prepared from the Lambus Daily Plan.'),button('Import trips',openImport,true),link('Template & instructions','setup.html#import',{class:'setup-link'}));const entry=state.entries.get(state.selectedId);const manage=entry?h('section',{class:'panel'},h('h2',{},'Selected trip'),h('p',{},entry.meta.name),downloadStatus(entry),(entry.trip||state.downloads.get(entry.id)?.revision===entry.revision)?h('p',{class:'small guide-summary'},guideSummary(entry.trip||state.downloads.get(entry.id).trip)):null,h('div',{class:'toolbar'},button(entry.archived?'Restore trip':'Archive trip',()=>archive(entry)),entry.archived?h('button',{type:'button',class:'button danger',disabled:deletesRunning.has(entry.id),onclick:()=>deleteArchivedTrip(entry)},deletesRunning.has(entry.id)?'Deleting…':'Delete'):null,state.downloads.has(entry.id)?null:button('Download',()=>startDownload(entry.id)))):null;const sync=h('section',{class:'panel'},h('h2',{},'About Glauco'),h('p',{},'Your shared, read-only travel guide.'),h('p',{class:'small'},'Version 1.3.0 · Built for the places you visit.'),link('Setup guide','setup.html'),h('div',{id:'conflicts'}));main.replaceChildren(h('div',{class:'settings-grid'},appearance,account,manage,downloads,imports,sync));patchDownloads();patchConflicts();}
function patchDownloads(){const list=$('downloadList');if(!list)return;list.replaceChildren();const existing=new Set();for(const d of [...state.downloads.values()].sort((a,b)=>a.name.localeCompare(b.name))){existing.add(d.id);const e=state.entries.get(d.id);list.append(h('div',{class:'download-row'},h('div',{},h('h3',{},d.name),h('p',{},`${sizeLabel(d.bytes)} · ${d.imageCount} images · Saved ${dateLabel(new Date(d.downloadedAt).toISOString().slice(0,10))}`),e&&e.revision!==d.revision?h('p',{class:'status warning'},'A newer guide is available'):null),h('div',{class:'toolbar'},e?button('Update',()=>startDownload(d.id,true)):null,button('Remove',()=>removeDownload(d.id)))));}
 for(const [id,running] of downloadsRunning){list.append(h('div',{class:'progress-wrap',id:`progress-${id}`},h('div',{class:'progress-head'},h('p',{},state.entries.get(id)?.meta.name||'Trip'),button('Cancel',()=>running.controller.abort())),h('p',{class:'small',id:`progressText-${id}`},'Preparing…'),h('progress',{id:`progressBar-${id}`,max:1,value:0})));if(running.progress)showProgress(id,running.progress);}
 if(!existing.size&&!downloadsRunning.size)list.append(h('p',{class:'small'},'No trips downloaded yet. Use Download on a trip to save it here.'));}
function patchConflicts(){const box=$('conflicts');if(!box)return;box.replaceChildren(...[...state.outbox.values()].filter(o=>o.conflict).map(o=>h('div',{class:'conflict-row'},h('h3',{},'Sync conflict'),h('p',{},`${state.entries.get(o.id)?.meta.name||'A trip'} was changed on another device. Your imported file remains the source copy.`),button('Use synced version',()=>resolveConflict(o)))));}
async function persist(entry){const pending=state.outbox.has(entry.id);await store.put('trips',{...entry,trip:pending?entry.trip:null});}
async function archive(entry){entry=state.entries.get(entry.id);if(!entry)return;if(state.outbox.has(entry.id)){notice('Sync this trip before changing its archive status.');return;}const previousRevision=entry.archiveRevision,previousArchived=entry.archived;entry.archived=!entry.archived;entry.archiveRevision=uid();const op={id:entry.id,type:'archive',expectedRevision:entry.revision,expectedArchiveRevision:previousRevision,previousArchived};state.outbox.set(entry.id,op);try{await store.change([{store:'trips',value:{...entry,trip:null}},{store:'outbox',value:op}]);patchTrips();notice(entry.archived?'Trip archived.':'Trip restored.');flush();}catch(error){state.outbox.delete(entry.id);entry.archived=previousArchived;entry.archiveRevision=previousRevision;notice('Could not save this change on your device.');}}
function guideSummary(trip){const sites=attractions(trip);return `${sites.reduce((n,{attraction:a})=>n+(a.comparisons||[]).length,0)} comparisons · ${sites.reduce((n,{attraction:a})=>n+(a.notice||[]).length,0)} things to notice · ${(trip.glossary||[]).length} glossary terms · ${sites.filter(({attraction:a})=>a.history?.length).length} timelines · ${sites.filter(({attraction:a})=>a.originality?.length).length} originality notes`;}
function openImport(){if(!state.user)return;importTrips=[];$('importPreview').replaceChildren();$('importError').textContent='';$('importFile').value='';$('confirmImport').disabled=true;showDialog($('importDialog'));}
$('importFile').addEventListener('change',async()=>{const file=$('importFile').files[0];$('confirmImport').disabled=true;$('importPreview').replaceChildren();$('importError').textContent='';importTrips=[];if(!file)return;try{if(file.size>MAX_FILE)throw new Error('The file is larger than 12 MB.');const epoch=state.epoch;const trips=parseImport(await file.text());if(epoch!==state.epoch||!$('importDialog').open)return;importTrips=trips;for(const trip of trips){const matches=[...state.entries.values()].filter(e=>e.id===trip.id||(e.meta.name.toLocaleLowerCase()===trip.name.toLocaleLowerCase()&&e.meta.year===trip.year));const select=h('select',{'data-import-id':trip.id,'aria-label':`Import action for ${trip.name}`},h('option',{value:'new'},matches.length?'Import as a new trip':'Import trip'));for(const e of matches)select.append(h('option',{value:e.id},`Replace ${e.meta.name}${e.archived?' (archived)':''}`));$('importPreview').append(h('div',{class:'import-row'},h('h3',{},trip.name),h('p',{},`${dateLabel(trip.startDate)} – ${dateLabel(trip.endDate)} · ${trip.days.length} days · ${attractions(trip).length} attractions`),h('p',{class:'small guide-summary'},guideSummary(trip)),select));}$('confirmImport').disabled=false;}catch(error){$('importError').textContent=error.message;}});
$('confirmImport').onclick=async()=>{if(busyImport||!importTrips.length)return;busyImport=true;$('confirmImport').disabled=true;$('importError').textContent='';const epoch=state.epoch;try{const selected=[...$('importPreview').querySelectorAll('select')].map(s=>s.value).filter(v=>v!=='new');if(new Set(selected).size!==selected.length)throw new Error('Choose a different replacement trip for each import.');const operations=[],created=[];
 for(const trip of importTrips){const choice=[...$('importPreview').querySelectorAll('select')].find(s=>s.dataset.importId===trip.id).value;const old=choice==='new'?null:state.entries.get(choice);if(old&&state.outbox.has(old.id))throw new Error('A replacement trip has an unsynced change. Sync it first.');const newId=old?.id||(!state.entries.has(trip.id)?trip.id:uid());const nextTrip={...trip,id:newId};const entry={id:newId,trip:nextTrip,meta:tripMeta(nextTrip),revision:uid(),archiveRevision:uid(),archived:old?.archived||false};const op={id:newId,type:'import',expectedRevision:old?.revision||null};operations.push({store:'trips',value:entry},{store:'outbox',value:op});created.push({entry,op});}
 if(epoch!==state.epoch||!state.user)throw new Error('Sign in again before importing.');await store.change(operations);if(epoch!==state.epoch)return;for(const {entry,op} of created){state.entries.set(entry.id,entry);state.outbox.set(entry.id,op);}busyImport=false;$('importDialog').close('imported');notice(`${created.length===1?'Trip':'Trips'} imported${navigator.onLine?'.':' and saved locally. Sync will resume online.'}`);state.selectedId=defaultTripId(created.map(c=>c.entry));state.selectionExplicit=true;location.hash=tripHref(state.selectedId).slice(1);renderRoute();flush();
 }catch(error){$('importError').textContent=error.message;}finally{busyImport=false;$('confirmImport').disabled=false;}};
async function startDownload(id,force=false){const entry=state.entries.get(id);if(!entry)return;if(downloadsRunning.has(id)){location.hash='/settings';renderSettings();return;}if(state.downloads.has(id)&&!force){location.hash='/settings';renderSettings();return;}if(!navigator.onLine){notice('Connect to the internet to download this trip.');return;}const controller=new AbortController(),epoch=state.epoch;downloadsRunning.set(id,{controller});location.hash='/settings';renderSettings();try{const trip=await ensureTrip(entry);controller.signal.throwIfAborted();if(epoch!==state.epoch)throw new Error('CANCELLED');const d=await downloadTrip({...entry,trip},p=>{const running=downloadsRunning.get(id);if(running)running.progress=p;showProgress(id,p);},controller.signal);if(epoch!==state.epoch||!state.entries.has(id)){await deleteDownload(id);return;}state.downloads.set(id,d);await navigator.storage?.persist?.();notice('Trip ready for offline reading.');}catch(error){if(epoch===state.epoch)notice(controller.signal.aborted?'Download cancelled.':error.message);}finally{downloadsRunning.delete(id);if(route().kind==='settings')patchDownloads();}}
function showProgress(id,p){const bar=$(`progressBar-${id}`),label=$(`progressText-${id}`);if(bar){bar.max=Math.max(1,p.total);bar.value=p.done?bar.max:p.completed;}if(label)label.textContent=`${p.completed} of ${p.total} images · ${sizeLabel(p.bytes)}`;}
async function removeDownload(id){if(downloadsRunning.has(id)){notice('Cancel or finish the download before removing it.');return;}if(!await ask('Remove this download?','The local guide and downloaded images will be removed. The shared trip remains available online.'))return;try{await deleteDownload(id);state.downloads.delete(id);const e=state.entries.get(id);if(e&&!state.outbox.has(id))e.trip=null;patchDownloads();notice('Download removed from this device.');}catch{notice('Could not remove the download. Try again.');}}
async function dropTrip(id){downloadsRunning.get(id)?.controller.abort();state.entries.delete(id);state.downloads.delete(id);state.outbox.delete(id);customsCountries.delete(id);await store.change([{store:'trips',type:'delete',id},{store:'outbox',type:'delete',id}]);await deleteDownload(id);}
async function deleteArchivedTrip(entry){const id=entry.id;entry=state.entries.get(id);if(!entry?.archived||deletesRunning.has(id))return;if(!navigator.onLine)return notice('Connect to the internet to delete this trip.');if(state.outbox.has(id))return notice('Sync this trip before deleting it.');if(downloadsRunning.has(id))return notice('Finish or cancel the download before deleting this trip.');const epoch=state.epoch,revision=entry.revision,archiveRevision=entry.archiveRevision;if(!await ask(`Delete ${entry.meta.name}?`,'This removes the trip from your shared collection and removes its downloads as devices sync. You can import the original JSON again.','Delete'))return;if(epoch!==state.epoch||!state.user)return;entry=state.entries.get(id);if(!entry?.archived||entry.revision!==revision||entry.archiveRevision!==archiveRevision||state.outbox.has(id)){renderSettings();notice('This trip changed. Review it before deleting.');return;}deletesRunning.add(id);renderSettings();try{await cloud.deleteArchived(entry,()=>epoch!==state.epoch||!state.user);if(epoch!==state.epoch)return;await dropTrip(id);patchTrips();notice('Trip deleted.');}catch(error){if(epoch!==state.epoch)return;notice(error.message==='CONFLICT'?'This trip changed on another device. Sync it before deleting.':'Could not delete the trip. Try again when connected.');}finally{deletesRunning.delete(id);if(state.user&&route().kind==='settings')renderSettings();}}
async function flush(){if(syncJob){syncAgain=true;return syncJob;}if(!state.user||!navigator.onLine)return;const epoch=state.epoch;syncJob=(async()=>{for(const op of [...state.outbox.values()]){if(epoch!==state.epoch||!navigator.onLine)return;if(op.conflict)continue;const e=state.entries.get(op.id);if(!e)continue;status('Syncing…');try{const cancelled=()=>epoch!==state.epoch||!state.user;if(op.type==='import')await cloud.saveImport(e,op.expectedRevision,cancelled);else await cloud.saveArchive(e,op.expectedRevision,op.expectedArchiveRevision,cancelled);if(cancelled())return;if(state.outbox.get(op.id)!==op)continue;await store.remove('outbox',op.id);if(cancelled())return;state.outbox.delete(op.id);await persist(e);patchTrips();}catch(error){if(epoch!==state.epoch)return;if(error.message==='CONFLICT'){op.conflict=true;await store.put('outbox',op);notice('A trip changed on another device. Review the conflict in Settings.');patchConflicts();}else{status('Sync paused · changes saved locally');return;}}}status(state.outbox.size?'Changes need attention':'Synced');})().finally(()=>{syncJob=null;if(syncAgain){syncAgain=false;setTimeout(flush,0);}});return syncJob;}
async function resolveConflict(op){if(!navigator.onLine)return notice('Connect to resolve this conflict.');if(!await ask('Use the synced version?','This replaces the unsynced local change. You can re-import your original file later.'))return;try{const meta=await cloud.remoteMeta(op.id);await store.remove('outbox',op.id);state.outbox.delete(op.id);if(meta&&!meta.deleted){const entry={id:meta.id,meta,revision:meta.revision,archiveRevision:meta.archiveRevision,archived:meta.archived,trip:null};state.entries.set(entry.id,entry);await persist(entry);}else await dropTrip(op.id);patchConflicts();patchTrips();status(state.outbox.size?'Changes need attention':'Synced');}catch(error){notice('Could not load the synced version. Try again.');}}
async function receive(metas){if(!state.user)return;const epoch=state.epoch;for(const rawMeta of metas){try{if(rawMeta?.deleted===true){const deletedId=text(rawMeta.id,100,'Trip ID',true);if(/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,99}$/.test(deletedId)&&!state.outbox.has(deletedId)){await dropTrip(deletedId);if(epoch!==state.epoch)return;}continue;}const meta=normalizeMeta(rawMeta);const id=text(meta.id,100,'Trip ID',true);if(!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,99}$/.test(id)||!Array.isArray(meta.days)||typeof meta.name!=='string'||typeof meta.revision!=='string')continue;const old=state.entries.get(id);if(state.outbox.has(id))continue;const changed=old?.revision!==meta.revision;const entry={id,meta,revision:meta.revision,archiveRevision:meta.archiveRevision,archived:meta.archived===true,trip:changed?null:old?.trip||null};state.entries.set(id,entry);await persist(entry);if(epoch!==state.epoch)return;if(state.selectionExplicit&&route().id===id&&changed&&!document.querySelector('dialog[open]')&&!$('tripSearch')?.value){renderRoute();}}catch{status('A synced trip could not be read.');}}
 state.loaded=true;const previous=state.selectedId;if(!state.selectionExplicit||!state.selectedId){state.selectedId=state.entries.has(initialTripId)?initialTripId:defaultTripId(state.entries.values());state.selectionExplicit=Boolean(state.selectedId);if(state.selectedId&&route().kind!=='settings'&&!(state.selectedId===initialTripId&&['day','attraction'].includes(route().kind))){const href=route().kind==='customs'?`#/customs/${state.selectedId}`:tripHref(state.selectedId);history.replaceState(null,'',href);routeKey=href;}}refreshSelector();if(previous!==state.selectedId||!route().id&&route().kind!=='settings')renderRoute();else if(route().kind==='settings'&&!document.querySelector('dialog[open]'))renderSettings();if(!state.outbox.size)status(navigator.onLine?'Synced':'Offline');}
async function authChanged(user){const epoch=++state.epoch;unsubscribe?.();unsubscribe=null;if(!cloud.authorized(user)){state.user=null;downloadsRunning.forEach(r=>r.controller.abort());state.entries.clear();state.downloads.clear();state.outbox.clear();state.selectedId=null;state.selectionExplicit=false;selectorSignature='';await store.clearPrivate();if(user){status('This Google account is not authorized for Glauco.');await cloud.logout();}else if(!state.status.includes('not authorized'))status('Sign in to open your guidebooks');gate();return;}
 state.user=user;status(navigator.onLine?'Syncing…':'Offline · saved guidebooks');try{const [entries,downloads,outbox]=await Promise.all([store.all('trips'),store.all('downloads'),store.all('outbox')]);if(epoch!==state.epoch)return;state.entries=new Map(entries.map(e=>[e.id,e]));state.downloads=new Map(downloads.map(e=>[e.id,e]));state.outbox=new Map(outbox.map(e=>[e.id,e]));state.loaded=true;state.selectionExplicit=Boolean(route().id&&state.entries.has(route().id));renderRoute();await removeOrphans();unsubscribe=cloud.listen(receive,error=>{status(`Sync unavailable (${error.code||'connection error'})`);notice('Your downloaded trips are still available. Check the Firebase rules and connection.');});flush();}catch{status('Browser storage unavailable');notice('Glauco needs browser storage to save imports and offline trips.');renderRoute();}}
async function signOut(){if(!await ask('Sign out?','Downloaded trips and private local data will be removed from this device.'+(state.outbox.size?' Unsynced changes will be discarded.':'')))return;const epoch=++state.epoch;unsubscribe?.();unsubscribe=null;state.user=null;downloadsRunning.forEach(r=>r.controller.abort());document.querySelectorAll('dialog[open]').forEach(d=>d.close());state.entries.clear();state.downloads.clear();state.outbox.clear();state.selectedId=null;state.selectionExplicit=false;selectorSignature='';status('Signing out…');gate();try{await cloud.logout();}catch{notice('Google sign-out needs a retry. Local guidebooks have been cleared.');}await store.clearPrivate();if(epoch<=state.epoch){status('Sign in to open your guidebooks');gate();}}
function syncThemeColor(){const root=document.documentElement;document.querySelector('meta[name=theme-color]').content=root.dataset.style==='explorer'?'#241810':root.dataset.theme==='light'?'#f5f7f6':'#0d0d0d';}
function applyTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem('glauco-theme',theme);}catch{}syncThemeColor();}
function applyStyle(style){document.documentElement.dataset.style=style==='explorer'?'explorer':'classic';try{localStorage.setItem('glauco-style',document.documentElement.dataset.style);}catch{}syncThemeColor();}
try{applyTheme(localStorage.getItem('glauco-theme')||'dark');}catch{applyTheme('dark');}
try{applyStyle(localStorage.getItem('glauco-style')||'classic');}catch{applyStyle('classic');}
window.addEventListener('online',()=>{status('Reconnecting…');if(state.user){cloud.setNetwork(true).then(flush).catch(()=>status('Sync unavailable'));}checkRelease();});window.addEventListener('offline',()=>{status('Offline · saved guidebooks');if(state.user)cloud.setNetwork(false).catch(()=>{});});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;let dismissed=false;try{dismissed=localStorage.getItem('glauco-install-dismissed')==='1';}catch{}if(!dismissed)$('installBanner').classList.remove('hidden');});$('installApp').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('installBanner').classList.add('hidden');};$('dismissInstall').onclick=()=>{$('installBanner').classList.add('hidden');try{localStorage.setItem('glauco-install-dismissed','1');}catch{}};
let registration,newRelease=false;const RELEASE='1.3.0';
async function checkRelease(){if(!navigator.onLine)return;try{const response=await fetch(`release.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)return;const release=await response.json();if(release.version!==RELEASE){newRelease=true;await registration?.update();$('releaseBanner').classList.remove('hidden');}}catch{}}
$('updateApp').onclick=async()=>{if(document.querySelector('dialog[open]')||downloadsRunning.size||busyImport){notice('Finish the open dialog or download before updating.');return;}if(state.outbox.size&&navigator.onLine)await flush();if(state.outbox.size){notice('Sync pending changes before updating.');return;}if(registration?.waiting)registration.waiting.postMessage({type:'ACTIVATE'});else if(newRelease)location.reload();};
if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').then(r=>{registration=r;if(r.waiting){newRelease=true;$('releaseBanner').classList.remove('hidden');}r.addEventListener('updatefound',()=>{const worker=r.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){newRelease=true;$('releaseBanner').classList.remove('hidden');}});});}).catch(()=>notice('Offline app support could not start. Use HTTPS and allow site storage.'));let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloading&&newRelease){reloading=true;location.reload();}});}
setTimeout(checkRelease,1800);setInterval(()=>{if(state.user&&navigator.onLine&&state.outbox.size)flush();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){checkRelease();if(state.user&&navigator.onLine)flush();}});
routeKey=location.hash||'#/trip';updateNav();scheduleToday();
if(cloud.configured()){status('Checking your account…');gate();try{cloud.startAuth(authChanged);}catch(error){status(`Firebase could not start (${error.code||'configuration error'})`);gate();}}
else{status('Firebase setup required');gate();}
