import {renderWildlifeView,clearWildlifeBrowsing} from './wildlife.js';
import {photoBackground} from './photo-background.js';
import {transition,initSwipeNav,initPhotoDismiss,syncPill,initTabBar,initMiniTitle,initGlossaryOrigin,initPhotoParallax} from './motion.js';
import {glossaryParts,historyTimeline,historyContext,tripTimeline,yearLabel} from './guide.js';
import {defaultTripId,orderedTrips,todayDay,dayNumber,dayTitle,localDateKey} from './navigation.js';
import {guidesForTrip} from './customs.js';
import {config} from './config.js';
import * as cloud from './firebase.js';
import * as store from './storage.js';
import {parseImport,normalizeTrip,tripMeta,attractions,uid,dateLabel,sizeLabel,MAX_FILE,text,normalizeMeta,guideTabs} from './model.js';
import {downloadTrip,deleteDownload,removeOrphans,storageReport,freeUpSpace} from './offline.js';
import {applyPhotoOverrides,normalizePhotoOverride,photoOverrideId,overrideRevision} from './photo-overrides.js';
import {uploadConfigured,uploadAttractionPhoto,destroyAttractionPhotos} from './cloudinary-upload.js';
import {normalizeWildlifeRecord,normalizeWildlifeNote,wildlifeRecordId,legacyWildlifeNoteId,applyWildlifeRecords} from './wildlife-tracking.js';
const $=id=>document.getElementById(id), main=$('main');
const state={user:null,entries:new Map(),downloads:new Map(),outbox:new Map(),overrides:new Map(),wildlifeRecords:new Map(),wildlifeNotes:new Map(),wildlifeOps:new Map(),selectedId:null,selectionExplicit:false,status:'Starting…',epoch:0,loaded:false};
let unsubscribe,unsubscribeOverrides,wildlifeUnsubscribers=[],syncJob,syncAgain=false,wildlifeSyncJob,wildlifeSyncAgain=false,routeKey='',viewToken=0,importTrips=[],noticeTimer,photoList=[],photoIndex=0,photoContext=null,busyImport=false,busyPhoto=false;
const scrolls=new Map(), downloadsRunning=new Map(), customsCountries=new Map(),placeCategories=new Map(),deletesRunning=new Set();
let selectorSignature='',initialTripId=route().id;
const isCambodiaTrip=value=>value?.id==='cambodia-thailand-2026'||['Cambodia/Thailand 2026','Cambodia & Thailand 2026','Cambodia & Thailand'].includes(value?.name);
const isPeruTrip=value=>value?.id==='peru-2027'||['Peru 2027','The Amazon and the Andes','The Amazon & the Andes'].includes(value?.name);
const isVeniceRomeGuide=value=>value?.id==='italy-venice-rome'||['Italy: Venice & Rome','Venice & Rome'].includes(value?.name);
const isPacificNorthwestGuide=value=>['Flora & Fauna of the Pacific Northwest','Washington & Oregon'].includes(value?.name);
const bundledTripHeader=value=>isCambodiaTrip(value)?'trip-headers/cambodia-thailand-2026-user-v2.webp':isPeruTrip(value)?'trip-headers/peru-2027-user.webp':isVeniceRomeGuide(value)?'trip-headers/venice-rome-user.webp':'';
const displayTripName=value=>isCambodiaTrip(value)?'Cambodia & Thailand':isPeruTrip(value)?'The Amazon & the Andes':isVeniceRomeGuide(value)?'Venice & Rome':isPacificNorthwestGuide(value)?'Washington & Oregon':value?.name||'';
const photoTarget=(entry,day,attraction,index=0)=>({'data-photo-trip':entry.id,'data-photo-day':day.id,'data-photo-attraction':attraction.id,'data-photo-index':index});
function viewingOverrides(entry){if(navigator.onLine)return state.overrides;const saved=state.downloads.get(entry.id);return saved&&(saved.photoRevision||0)===overrideRevision(state.overrides,entry.id)?state.overrides:new Map();}
function wildlifePhotoRevision(guideId){return Math.max(0,...[...state.wildlifeRecords.values()].filter(value=>value.guideId===guideId&&value.photo).map(value=>value.updatedAt||0));}
function guideAssetRevision(guideId){return Math.max(overrideRevision(state.overrides,guideId),wildlifePhotoRevision(guideId));}
function viewingWildlifeRecords(entry){if(navigator.onLine)return state.wildlifeRecords;const saved=state.downloads.get(entry.id);return saved&&(saved.photoRevision||0)===guideAssetRevision(entry.id)?state.wildlifeRecords:new Map();}
function syncTripPalette(){const meta=state.entries.get(state.selectedId)?.meta;if(isPeruTrip(meta))document.documentElement.dataset.tripPalette='peru';else if(isVeniceRomeGuide(meta))document.documentElement.dataset.tripPalette='italy';else if(isCambodiaTrip(meta))document.documentElement.dataset.tripPalette='cambodia';else delete document.documentElement.dataset.tripPalette;}
const icons={book:'M4 4h6l2 2 2-2h6v16h-6l-2 2-2-2H4zM12 6v16',back:'m14 5-7 7 7 7',arrow:'m9 5 7 7-7 7',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',photo:'M3 3h18v18H3zM3 17l6-6 5 5 3-3 4 4M8 7h.01'};
function h(tag,props={},...children){const e=document.createElement(tag);for(const [k,v] of Object.entries(props)){if(v==null)continue;if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='disabled')e.disabled=v;else e.setAttribute(k,String(v));}for(const c of children.flat(Infinity))if(c!=null)e.append(c instanceof Node?c:document.createTextNode(String(c)));return e;}
function icon(name){const e=document.createElementNS('http://www.w3.org/2000/svg','svg');e.setAttribute('viewBox','0 0 24 24');e.setAttribute('aria-hidden','true');const p=document.createElementNS(e.namespaceURI,'path');p.setAttribute('d',icons[name]||icons.book);e.append(p);return e;}
function button(label,fn,primary=false){return h('button',{type:'button',class:`button ${primary?'primary':''}`,onclick:fn},label);}
function link(label,href,props={}){return h('a',{href,...props},label);}
function external(label,href){return link(label,href,{target:'_blank',rel:'noopener noreferrer'});}
function openGlossary(term){$('glossaryTitle').textContent=term.term;$('glossaryDefinition').textContent=term.definition;const picture=$('glossaryImage'),source=term.photo?.url||'';picture.classList.toggle('hidden',!source);if(source){picture.src=source;picture.alt=term.photo.alt||term.term;}else{picture.removeAttribute('src');picture.alt='';}showDialog($('glossaryDialog'));}
function guideText(trip,value){return glossaryParts(value,trip.glossary).map(part=>part.term?h('button',{type:'button',class:'glossary-word','aria-haspopup':'dialog','aria-controls':'glossaryDialog',onclick:()=>openGlossary(part.term)},part.text):part.text);}
function guideParagraph(trip,value,props={}){return h('p',props,guideText(trip,value));}
function image(src,alt,cls=''){
 if(!src)return h('div',{class:`placeholder ${cls}`},icon('photo'));
 const img=h('img',{src,alt,loading:'lazy',decoding:'async',class:`${cls}${cls?' ':''}img-loading`,'aria-busy':'true'});let settled=false;
 const ready=()=>{if(settled)return;settled=true;img.classList.remove('img-loading');img.classList.add('img-in');img.removeAttribute('aria-busy');};
 const failed=()=>{if(settled)return;settled=true;img.replaceWith(h('div',{class:`placeholder ${cls}`,'aria-label':`${alt || 'Image'} unavailable`},icon('photo')));};
 img.addEventListener('load',ready,{once:true});img.addEventListener('error',failed,{once:true});queueMicrotask(()=>{if(img.complete)(img.naturalWidth?ready:failed)();});return img;
}
function hideNotice(){const n=$('notice');n.classList.add('leaving');setTimeout(()=>{if(n.classList.contains('leaving')){n.classList.add('hidden');n.classList.remove('leaving');}},220);}
function notice(message){const n=$('notice');n.textContent=message;n.classList.remove('hidden','leaving');clearTimeout(noticeTimer);noticeTimer=setTimeout(hideNotice,6500);}
function swapText(el,message){if(!el||el.textContent===message)return;el.textContent=message;el.classList.remove('swap');void el.offsetWidth;el.classList.add('swap');}
function status(message){state.status=message;swapText($('connection'),message);swapText($('syncStatus'),message);}
function route(){const parts=(location.hash.slice(1)||'/trip').split('/').filter(Boolean);return {kind:parts[0]||'trip',id:parts[1],day:parts[2],attraction:parts[3]};}
const tripHref=id=>`#/trip/${id}`,dayHref=(id,day)=>`#/day/${id}/${day}`,attrHref=(id,day,a)=>`#/attraction/${id}/${day}/${a}`;
const mainTabHref=(tab,id)=>tab==='customs'?`#/customs/${id}`:tab==='wildlife'?`#/wildlife/${id}`:tripHref(id);
function back(label,href){return link([icon('back'),label],href,{class:'back-link'});}
function skeleton(){const block=cls=>h('div',{class:`sk ${cls}`});return h('div',{class:'skeleton',role:'status','aria-busy':'true'},h('span',{class:'sr-only'},'Opening your guide…'),block('sk-search'),...[0,1,2].map(()=>h('div',{class:'sk-card'},block('sk-line'),block('sk-line short'),h('div',{class:'sk-row'},block('sk-thumb'),block('sk-thumb'),block('sk-thumb')))));}
function empty(title,message,action){return h('div',{class:'empty'},icon('book'),h('h1',{},title),h('p',{},message),action);}
function selectDefault(){if(!state.entries.has(state.selectedId))state.selectedId=defaultTripId(state.entries.values());}
function refreshSelector(){
 selectDefault();const select=$('tripSelect');$('tripSelector').classList.toggle('hidden',!state.user||route().kind!=='settings');
 const entries=orderedTrips(state.entries.values());const signature=JSON.stringify([state.selectedId,...entries.map(e=>[e.id,displayTripName(e.meta),e.meta.guideType,e.meta.startDate,e.meta.endDate,e.meta.tabs,e.archived])]);
 if(signature!==selectorSignature){selectorSignature=signature;select.replaceChildren();
  if(!entries.length)select.append(h('p',{class:'trip-menu-empty'},'No guides yet'));
  for(const [label,filter] of [['Guides',e=>!e.archived],['Archived',e=>e.archived]]){const matches=entries.filter(filter);if(!matches.length)continue;select.append(h('p',{class:'trip-menu-label'},label));for(const e of matches){const selected=e.id===state.selectedId,type=e.meta.guideType==='trip'||!e.meta.guideType?'Trip':'Guide';select.append(h('button',{type:'button',class:`trip-option${selected?' selected':''}`,'aria-pressed':selected,onclick:()=>selectGuide(e.id)},h('span',{class:'trip-option-title'},displayTripName(e.meta)),h('span',{class:'trip-option-type'},type)));}}
 }
 const selectedMeta=state.entries.get(state.selectedId)?.meta,selectedType=selectedMeta?.guideType,tabs=selectedMeta?guideTabs(selectedMeta):['trip','customs','wildlife'],primaryTab=document.querySelector('[data-tab=trip]');primaryTab.href=state.selectedId?tripHref(state.selectedId):'#/trip';primaryTab.querySelector('span').textContent=selectedType==='destination'?'Guide':selectedType==='wildlife'?'Field Guide':'Trip';
 document.querySelector('[data-tab=customs]').href=state.selectedId?`#/customs/${state.selectedId}`:'#/customs';document.querySelector('[data-tab=wildlife]').href=state.selectedId?`#/wildlife/${state.selectedId}`:'#/wildlife';for(const tab of ['trip','customs','wildlife'])document.querySelector(`[data-tab=${tab}]`).classList.toggle('hidden',!tabs.includes(tab));document.documentElement.style.setProperty('--main-tab-count',String(tabs.length+1));refreshToday();
}
function selectGuide(id){if(!state.entries.has(id)||id===state.selectedId)return;state.selectedId=id;state.selectionExplicit=true;selectorSignature='';scrolls.clear();updateNav();renderSettings();window.scrollTo(0,0);}
function refreshToday(){const day=state.user?todayDay(state.entries.get(state.selectedId)):null;const banner=$('todayShortcut');banner.classList.toggle('hidden',!day);document.body.classList.toggle('has-today-shortcut',Boolean(day));if(day){banner.href=dayHref(state.selectedId,day.id);banner.replaceChildren(h('span',{},h('strong',{},'Today'),h('span',{},dayTitle(state.entries.get(state.selectedId).meta,day))),icon('arrow'));}}
function updateNav(){const kind=route().kind;const tab=['settings','customs','wildlife'].includes(kind)?kind:'trip';document.body.classList.toggle('trips-view',tab!=='settings');document.body.classList.toggle('settings-view',kind==='settings');document.querySelectorAll('[data-tab]').forEach(a=>{const active=a.dataset.tab===tab;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});refreshSelector();syncTripPalette();syncPill();}
let midnightTimer;
function scheduleToday(){clearTimeout(midnightTimer);refreshToday();const now=new Date(),next=new Date(now);next.setHours(24,0,0,50);midnightTimer=setTimeout(scheduleToday,next-now);}
window.addEventListener('focus',scheduleToday);document.addEventListener('visibilitychange',()=>{if(!document.hidden)scheduleToday();});
const tabBar=document.querySelector('.main-nav');new ResizeObserver(()=>document.documentElement.style.setProperty('--tabbar-height',`${tabBar.getBoundingClientRect().height}px`)).observe(tabBar);
function gate(){resetAttractionBackground();updateNav();main.replaceChildren(h('section',{class:'panel auth-card'},h('a',{class:'brand',href:'#/trips'},icon('book'),'Carrots'),h('h1',{},'A guide for every stop.'),h('p',{},'Stories, details, and things to notice. Your personal guidebook, ready to take along.'),cloud.configured()?button('Sign in with Google',signIn,true):h('p',{},'Connect your Firebase project to get started.'),h('p',{class:'small',id:'gateMessage'},state.status),link(cloud.configured()?'Setup & import guide':'Set up Carrots','setup.html',{class:'setup-link'})));}
async function signIn(){if(!cloud.configured())return;try{await cloud.login();}catch(error){status(error.code==='auth/popup-blocked'?'Allow the Google sign-in popup, then try again.':`Sign-in did not finish (${error.code||'connection error'}). Check Firebase setup.`);gate();}}
async function ask(title,message,confirmLabel='Continue'){$('confirmTitle').textContent=title;$('confirmText').textContent=message;$('confirmDialog').querySelector('button[value=confirm]').textContent=confirmLabel;return new Promise(resolve=>{const dialog=$('confirmDialog');dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true});showDialog(dialog);});}
function showDialog(dialog){dialog.returnValue='';history.pushState({...history.state,glaucoDialog:dialog.id},'',location.href);dialog.showModal();}
for(const dialog of document.querySelectorAll('dialog')){
 dialog.addEventListener('click',event=>{if(event.target===dialog && !(dialog.id==='importDialog'&&busyImport))dialog.close('cancel');});
 dialog.addEventListener('cancel',event=>{if(dialog.id==='importDialog'&&busyImport)event.preventDefault();});
 dialog.addEventListener('close',()=>{if(history.state?.glaucoDialog===dialog.id)history.back();});
}
window.addEventListener('popstate',()=>{document.querySelectorAll('dialog[open]').forEach(d=>{if(history.state?.glaucoDialog!==d.id)d.close('cancel');});});
window.addEventListener('hashchange',()=>{const newKey=location.hash||'#/trip';if(newKey===routeKey)return;scrolls.set(routeKey,window.scrollY);const oldKey=routeKey;routeKey=newKey;const restore=()=>window.scrollTo(0,scrolls.get(routeKey)||0);transition(main,oldKey,newKey,async()=>{await renderRoute();restore();},()=>{renderRoute();requestAnimationFrame(restore);});});
initSwipeNav(main);initPhotoDismiss($('photoDialog'));initTabBar();initMiniTitle(main);initGlossaryOrigin($('glossaryDialog'));initPhotoParallax(main);
function downloadStatus(entry){const d=state.downloads.get(entry.id);if(!d)return h('span',{class:'status'},state.outbox.has(entry.id)?'Waiting to sync':'Not downloaded');const current=d.revision===entry.revision&&(d.photoRevision||0)===guideAssetRevision(entry.id),ready=current&&!d.partial,partial=d.partial&&current;return h('span',{class:`status ${ready?'ready':'warning'}`},ready?h('span',{class:'check','aria-hidden':'true'},'✓'):null,`${partial?`Partly saved · ${d.imageCount} of ${d.photoTotal} photos`:ready?' Offline ready':'Download update available'} · ${sizeLabel(d.bytes)}`);}
function patchTrips(){const previous=state.selectedId;refreshSelector();if(previous!==state.selectedId||route().kind==='trips'||(route().kind==='trip'&&!route().id))renderRoute();else if(route().kind==='settings')renderSettings();}
function titleBlock(title,subtitle,action,subtitleClass=''){return h('div',{class:'page-heading'},h('div',{},h('h1',{},title),h('p',{class:`muted${subtitleClass?` ${subtitleClass}`:''}`},subtitle)),action);}
function tripDateRange(start,end){
 const parts=value=>value.split('-').map(Number),[startYear,startMonth,startDay]=parts(start),[endYear,endMonth,endDay]=parts(end);
 const month=value=>new Intl.DateTimeFormat(undefined,{month:'long',timeZone:'UTC'}).format(new Date(Date.UTC(2000,value-1,1)));
 if(start===end)return `${month(startMonth)} ${startDay}, ${startYear}`;
 if(startYear===endYear&&startMonth===endMonth)return `${month(startMonth)} ${startDay}-${endDay}, ${endYear}`;
 if(startYear===endYear)return `${month(startMonth)} ${startDay} - ${month(endMonth)} ${endDay}, ${endYear}`;
 return `${month(startMonth)} ${startDay}, ${startYear} - ${month(endMonth)} ${endDay}, ${endYear}`;
}
function visibleEntry(id){return state.entries.get(id);}
async function ensureTrip(entry){if(!navigator.onLine){const d=state.downloads.get(entry.id);if(d)return d.trip;if(state.outbox.has(entry.id)&&entry.trip)return entry.trip;throw new Error('Download this guide while online to read it without a connection.');}if(entry.trip)return entry.trip;const epoch=state.epoch,revision=entry.revision;const trip=await cloud.readRemote({...entry.meta,revision});if(epoch!==state.epoch||!state.user||state.entries.get(entry.id)?.revision!==revision)throw new Error('The guide changed. Open it again.');entry.trip=trip;return trip;}
async function renderRoute(){
 resetAttractionBackground();
 const token=++viewToken;let r=route();const keepComparisons=main.firstElementChild?.dataset.articleKey===`${r.id}/${r.day}/${r.attraction}`&&$('comparisonsTab')?.getAttribute('aria-selected')==='true';
 if(state.user){if(r.id&&state.entries.has(r.id)){state.selectedId=r.id;}selectDefault();
  if(!['settings','customs','wildlife','trip','day','attraction','timeline'].includes(r.kind)||((r.kind!=='settings')&&state.selectedId&&r.id!==state.selectedId)){
   const href=r.kind==='customs'||r.kind==='wildlife'?`#/${r.kind}/${state.selectedId}`:r.kind==='timeline'&&state.selectedId?`#/timeline/${state.selectedId}`:state.selectedId?tripHref(state.selectedId):'#/trip';history.replaceState(null,'',href);routeKey=href;r=route();
  }
 }
 updateNav();if(!state.user)return gate();if(r.kind==='settings')return renderSettings();
 const entry=visibleEntry(state.selectedId);
 if(!entry){main.replaceChildren(empty('Your next guide starts here.','Import a Carrots guidebook file in Settings to begin.',link('Open Settings','#/settings',{class:'button primary'})));return;}
 const configuredTabs=guideTabs(entry.meta),availableTabs=['trip','customs','wildlife'].filter(tab=>configuredTabs.includes(tab)),requestedTab=r.kind==='customs'||r.kind==='wildlife'?r.kind:'trip';if(!availableTabs.includes(requestedTab)){const href=mainTabHref(availableTabs[0],entry.id);history.replaceState(null,'',href);routeKey=href;r=route();updateNav();}
 let trip;
 try{if(!entry.trip&&navigator.onLine)main.replaceChildren(skeleton());trip=applyWildlifeRecords(applyPhotoOverrides(await ensureTrip(entry),viewingOverrides(entry)),viewingWildlifeRecords(entry));}catch(error){if(token===viewToken)main.replaceChildren(empty('This guide needs a connection.',error.message,navigator.onLine?button('Try again',renderRoute):link('Manage downloads','#/settings')));return;}
 if(token!==viewToken)return;
 if(trip.guideType==='wildlife'&&r.kind!=='wildlife'){const href=`#/wildlife/${entry.id}`;history.replaceState(null,'',href);routeKey=href;renderWildlife(entry,trip);main.focus({preventScroll:true});return;}
 if(trip.guideType==='destination'&&r.kind==='timeline'){history.replaceState(null,'',tripHref(entry.id));routeKey=location.hash;r=route();}
 if(r.kind==='customs')renderCustoms(entry,trip);
 else if(r.kind==='wildlife')renderWildlife(entry,trip);
 else if(r.kind==='timeline')renderTimeline(entry,trip);
 else if(r.kind==='trip')renderTrip(entry,trip);
 else {const day=trip.days.find(d=>d.id===r.day),destination=trip.guideType==='destination';if(!day){main.replaceChildren(back(destination?'Guide':'Trip',tripHref(entry.id)),empty(destination?'Place not found':'Day not found',destination?'Choose another place from the guide.':'Choose another day from the trip.'));return;}if(r.kind==='day')renderDay(entry,trip,day);else{const a=day.attractions.find(a=>a.id===r.attraction);if(a)renderAttraction(entry,trip,day,a,keepComparisons);else main.replaceChildren(back(destination?'Place':'Day',dayHref(entry.id,day.id)),empty('Attraction not found',destination?'Choose another attraction from this place.':'Choose another attraction from this day.'));}}
 main.focus({preventScroll:true});
}
function renderWildlife(entry,trip){renderWildlifeView(entry,trip,route(),{h,link,back,image,main,empty,guideParagraph,external,dateLabel,applyBackground:applyAttractionBackground,tracker:wildlifeTracker(entry,trip),showPhotos:(photos,index,name,context=null)=>{photoContext=context?{...context,entry}:null;photoList=photos.map(p=>({...p,alt:name}));photoIndex=index;showPhoto();showDialog($('photoDialog'));}});}
const wildlifeKinds={records:{map:'wildlifeRecords',store:'wildlifeRecords',remote:'wildlifeRecords',normalize:normalizeWildlifeRecord},notes:{map:'wildlifeNotes',store:'wildlifeSightings',remote:'wildlifeSightings',normalize:normalizeWildlifeNote}};
async function changeWildlife(kind,type,valueOrId){const setup=wildlifeKinds[kind],id=type==='delete'?valueOrId:valueOrId.id,op={id:`${kind}:${id}`,kind,docId:id,type,...(type==='set'?{value:valueOrId}:{}),updatedAt:Date.now()},map=state[setup.map];if(type==='delete')map.delete(id);else map.set(id,valueOrId);state.wildlifeOps.set(op.id,op);await store.change([{store:setup.store,...(type==='delete'?{type:'delete',id}:{value:valueOrId})},{store:'wildlifeOps',value:op}]);flushWildlife();}
const localDate=value=>{const date=new Date(value),year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,'0'),day=String(date.getDate()).padStart(2,'0');return `${year}-${month}-${day}`;};
let legacyNoteMigrationJob=null;
async function migrateLegacyWildlifeNotes(){
 if(legacyNoteMigrationJob)return legacyNoteMigrationJob;
 legacyNoteMigrationJob=(async()=>{for(const old of [...state.wildlifeRecords.values()]){if(!old.notes||old.notesMigrated)continue;const id=legacyWildlifeNoteId(old.guideId,old.speciesId);if(!state.wildlifeNotes.has(id))await changeWildlife('notes','set',normalizeWildlifeNote({id,guideId:old.guideId,speciesId:old.speciesId,date:localDate(old.updatedAt||Date.now()),note:old.notes,createdAt:old.updatedAt||Date.now(),updatedAt:Date.now()}));await changeWildlife('records','set',normalizeWildlifeRecord({...old,seen:true,seenMigrated:true,notesMigrated:true,updatedAt:Date.now()}));}})().finally(()=>{legacyNoteMigrationJob=null;});return legacyNoteMigrationJob;
}
function wildlifeTracker(entry,trip){
 const setSeen=async(species,seen)=>{const id=wildlifeRecordId(entry.id,species.id),old=state.wildlifeRecords.get(id)||{id,guideId:entry.id,speciesId:species.id};await changeWildlife('records','set',normalizeWildlifeRecord({...old,seen,seenMigrated:true,updatedAt:Date.now()}));};
 return {
  records:state.wildlifeRecords,notes:state.wildlifeNotes,
  toggleSeen:async species=>{const seen=state.wildlifeRecords.get(wildlifeRecordId(entry.id,species.id))?.seen===true;await setSeen(species,!seen);notice(seen?'Marked not seen.':'Marked seen.');renderRoute();},
  saveNote:(species,draft)=>saveWildlifeNote(entry,species,draft,setSeen),
  deleteNote:(species,note)=>deleteWildlifeNote(species,note),
  replacePhoto:async(species,file)=>replaceWildlifePhoto(entry,species,file)
 };
}
async function saveWildlifeNote(entry,species,draft,setSeen){
 if(busyPhoto)throw new Error('Wait for the current photo to finish.');const existing=draft.existing,id=existing?.id||uid(),oldPhoto=existing?.photo;let photo=draft.removePhoto?null:oldPhoto,uploaded=null,token=null;
 if(draft.file){if(!navigator.onLine)throw new Error('Connect to attach a photo.');busyPhoto=true;notice('Preparing your wildlife note photo…');try{token=await cloud.authToken();uploaded=await uploadAttractionPhoto(draft.file,{tripId:entry.id,attractionId:`wildlife_note_${id}_${species.id}`},token);photo={url:uploaded.url,thumbnailUrl:uploaded.thumbnailUrl,publicId:uploaded.publicId};}catch(error){busyPhoto=false;throw error;}}
 else if(draft.removePhoto&&oldPhoto?.publicId){if(!navigator.onLine)throw new Error('Connect to remove this photo.');token=await cloud.authToken();}
 try{const now=Date.now(),value=normalizeWildlifeNote({id,guideId:entry.id,speciesId:species.id,date:draft.date,note:draft.note,photo,createdAt:existing?.createdAt||now,updatedAt:now});await changeWildlife('notes','set',value);await setSeen(species,true);if(oldPhoto?.publicId&&oldPhoto.publicId!==photo?.publicId)destroyAttractionPhotos([oldPhoto.publicId],token);notice(existing?'Note updated.':'Note added.');renderRoute();}
 catch(error){if(uploaded?.publicId&&token)destroyAttractionPhotos([uploaded.publicId],token);throw error;}finally{busyPhoto=false;}
}
async function deleteWildlifeNote(species,note){if(!await ask('Delete this note?','This permanently removes the note and its attached photo.','Delete'))return;if(note.photo?.publicId&&!navigator.onLine)return notice('Connect to delete a note with a photo.');try{const token=note.photo?.publicId?await cloud.authToken():null;await changeWildlife('notes','delete',note.id);if(note.photo?.publicId)destroyAttractionPhotos([note.photo.publicId],token);notice('Note deleted.');renderRoute();}catch(error){notice(error.message||'The note could not be deleted.');}}
async function replaceWildlifePhoto(entry,species,file){if(busyPhoto)return;if(!navigator.onLine)return notice('Connect to replace a wildlife photo.');busyPhoto=true;notice('Preparing your wildlife photo…');try{const token=await cloud.authToken(),uploaded=await uploadAttractionPhoto(file,{tripId:entry.id,attractionId:`wildlife_${species.id}`},token),id=wildlifeRecordId(entry.id,species.id),old=state.wildlifeRecords.get(id)||{id,guideId:entry.id,speciesId:species.id};await changeWildlife('records','set',normalizeWildlifeRecord({...old,photo:{url:uploaded.url,thumbnailUrl:uploaded.thumbnailUrl,publicId:uploaded.publicId},updatedAt:Date.now()}));if(old.photo?.publicId&&old.photo.publicId!==uploaded.publicId)destroyAttractionPhotos([old.photo.publicId],token);notice('Wildlife cover photo updated.');if($('photoDialog').open)$('photoDialog').close();renderRoute();}catch(error){notice(error.message||'The wildlife photo could not be uploaded.');}finally{busyPhoto=false;}}
function glossaryEntry(g){
 const copy=h('div',{},h('dt',{},g.term),h('dd',{},g.definition));
 if(!g.photo)return h('div',{class:'glossary-term'},copy);
 const visual=h('button',{type:'button',class:'glossary-visual','aria-label':`Open ${g.term} definition`,onclick:()=>openGlossary(g)},image(g.photo.thumbnailUrl||g.photo.url,g.photo.alt||g.term));
 return h('div',{class:'glossary-term has-image'},visual,copy);
}
function renderCustoms(entry,trip){
 const destination=trip.guideType==='destination';
 const glossary=(trip.glossary||[]).length?h('section',{class:'panel trip-glossary'},h('h2',{},`Key terms for this ${destination?'guide':'trip'}`),h('dl',{},...trip.glossary.map(glossaryEntry))):null;
 const guides=guidesForTrip(trip);if(!guides.length){main.replaceChildren(glossary,empty('A local guide is not available yet.','Import an updated guidebook with customs content to add local tips and useful phrases. Built-in guides cover Cambodia, Thailand and Peru.'));return;}
 const selected=guides.find(g=>g.id===customsCountries.get(entry.id))||guides[0];
 const countries=h('div',{class:'segmented country-tabs','aria-label':'Country or region'},...guides.map(g=>h('button',{type:'button',class:g===selected?'active':'','aria-pressed':g===selected,onclick:()=>{customsCountries.set(entry.id,g.id);renderCustoms(entry,trip);}},g.name)));
 const article=h('article',{class:'customs-guide'},h('h2',{},selected.name),selected.intro?guideParagraph(trip,selected.intro,{class:'muted'}):null,...selected.sections.map(s=>h('section',{class:'panel guide-text'},h('h2',{},s.heading),...s.paragraphs.map(p=>guideParagraph(trip,p)))));
 if(selected.phrases.length)article.append(h('section',{class:'panel phrase-guide'},h('h2',{},`Useful ${selected.language}`),selected.phraseNote?guideParagraph(trip,selected.phraseNote,{class:'small'}):null,h('dl',{class:'phrase-list'},...selected.phrases.map(p=>h('div',{class:'phrase'},h('dt',{},p.meaning),h('dd',{},h('span',{class:'native-phrase',lang:selected.lang},p.native),p.pronunciation?h('span',{class:'phrase-sound'},p.pronunciation):null))))));
 article.append(h('section',{class:'sources'},selected.sources.length?h('h2',{},'Sources and further reading'):null,h('p',{class:'small'},`Checked ${dateLabel(selected.researchedAt)}. Transport options and venue guidance can change.`),selected.sources.length?h('ul',{},...selected.sources.map(s=>h('li',{},external(s.title,s.url)))):null));
 main.replaceChildren(glossary,guides.length>1?countries:null,article);
}
function renderTrip(entry,trip){
 const destination=trip.guideType==='destination',showHero=!destination||isVeniceRomeGuide(trip),localHeader=bundledTripHeader(trip),headerUrl=localHeader||trip.headerUrl||trip.coverUrl,heroImage=showHero?image(headerUrl,'',`trip-hero-image${isPeruTrip(trip)?' trip-hero-image-cover':''}`):null;
 if(heroImage instanceof HTMLImageElement){heroImage.loading='eager';heroImage.fetchPriority='high';}
 const hero=showHero?h('section',{class:'trip-hero'},heroImage,h('div',{class:'trip-hero-copy'},h('h1',{},...(isPeruTrip(trip)?['The Amazon &',h('br'),'the Andes']:[displayTripName(trip)])),h('p',{},destination?'Travel Guide':tripDateRange(trip.startDate,trip.endDate)))):null;
 const search=h('input',{id:'tripSearch',type:'search',placeholder:`Search this ${destination?'guide':'trip'}`,'aria-label':`Search this ${destination?'guide':'trip'}`,maxlength:150});
 const clear=h('button',{type:'button',class:'hidden','aria-label':'Clear search',onclick:()=>{search.value='';search.focus();updateSearch();}},'×');
 const days=h('div',{id:'days',class:`days ${destination?'place-days':'trip-days'}`},...trip.days.map(d=>{
  const heading=destination?link([h('div',{},h('h2',{},dayTitle(trip,d))),icon('arrow')],dayHref(entry.id,d.id),{class:'day-heading'}):link([h('p',{class:'day-meta'},`Day ${dayNumber(trip,d.id)} • ${dateLabel(d.date,{weekday:'long',month:'long',day:'numeric'})}`),h('h2',{},d.title)],dayHref(entry.id,d.id),{class:'day-heading'});
  const pictured=d.attractions.filter(a=>a.photos.length),strip=pictured.length?h('div',{class:'thumb-viewport'},h('div',{class:'thumb-strip','aria-label':destination?`Entries in ${d.title}`:`Attractions on ${dateLabel(d.date)}`},...pictured.map(a=>link(image(a.photos[0].thumbnailUrl||a.photos[0].url,''),attrHref(entry.id,d.id,a.id),{class:'thumbnail','aria-label':a.name,title:a.name,...photoTarget(entry,d,a)})))):null;
  return h('article',{class:`day-card ${destination?'place-card':'trip-day-card'}`,onclick:event=>{if(!event.target.closest('a,button')&&!event.target.closest('.thumb-strip')&&!window.getSelection()?.toString())location.hash=dayHref(entry.id,d.id).slice(1);}},heading,strip);
 }));
 const results=h('div',{id:'searchResults',class:'hidden','aria-live':'polite'});
 if(hero){document.body.classList.add('trip-detail-view');document.body.style.setProperty('--trip-header-image',`url(${JSON.stringify(headerUrl)})`);syncThemeColor();}
 const searchBox=h('div',{class:'search-wrap'},icon('search'),search,clear),tabs=destination?null:viewTabs(entry,trip,'days'),controls=h('div',{class:'trip-controls'},searchBox,tabs);
 main.replaceChildren(...[hero,controls,results,days].filter(Boolean));
 if(!navigator.onLine){const saved=state.downloads.get(entry.id),current=saved?.revision===entry.revision&&(saved.photoRevision||0)===overrideRevision(state.overrides,entry.id);main.insertBefore(h('p',{class:'offline-note'},current?'Reading your downloaded guide offline.':`Reading the saved version of this ${destination?'guide':'trip'}. Reconnect to check for updates.`),days);}
 const searchable=attractions(trip).map(item=>({...item,text:[item.attraction.name,item.attraction.location,item.attraction.neighborhood,...item.attraction.summary,...(item.attraction.notice||[]),...(item.attraction.comparisons||[]).flatMap(c=>c.paragraphs),...(item.attraction.originality||[]),...(item.attraction.history||[]).flatMap(event=>[event.label,event.title,event.text]),...item.attraction.facts.flatMap(f=>[f.label,f.value]),...item.attraction.sections.flatMap(s=>[s.heading,...s.paragraphs])].join(' ').toLocaleLowerCase()}));
 function updateSearch(){clear.classList.toggle('hidden',!search.value.length);const query=search.value.trim().toLocaleLowerCase();days.classList.toggle('hidden',Boolean(query));results.classList.toggle('hidden',!query);if(!query){results.replaceChildren();return;}const matches=searchable.filter(a=>a.text.includes(query));results.replaceChildren(h('p',{class:'small'},`${matches.length} ${destination?(matches.length===1?'entry':'entries'):(matches.length===1?'attraction':'attractions')} found`),...matches.map(({day,attraction:a})=>link([image(a.photos[0]?.thumbnailUrl,'',''),h('div',{},h('h3',{},a.name),h('p',{},destination?day.title:`${dateLabel(day.date)} · ${dayTitle(trip,day)}`))],attrHref(entry.id,day.id,a.id),{class:'result',...photoTarget(entry,day,a)})));}
 search.addEventListener('input',updateSearch);
}
function viewTabs(entry,trip,current,timeline=tripTimeline(trip,localDateKey())){if(trip.guideType==='destination'||!timeline.events.length)return null;return h('div',{class:'segmented view-tabs','aria-label':'Trip view'},...[['days','Days',tripHref(entry.id)],['timeline','Timeline',`#/timeline/${entry.id}`]].map(([key,label,href])=>h('button',{type:'button',class:key===current?'active':'','aria-pressed':key===current,onclick:()=>{if(key!==current)location.hash=href.slice(1);}},label)));}
function renderTimeline(entry,trip){
 const timeline=tripTimeline(trip,localDateKey()),tabs=viewTabs(entry,trip,'timeline',timeline);
 if(!timeline.events.length){main.replaceChildren(empty('No history in this trip yet','This trip file has no historical milestones for its sites.',link('Back to days',tripHref(entry.id),{class:'button primary'})));return;}
 const span=timeline.max-timeline.min,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const dots=timeline.events.map(e=>{const dot=h('button',{type:'button',class:`ruler-dot ${e.status}`,'aria-label':`${e.attraction.name}, ${yearLabel(e.year)}: ${e.title}`,title:`${yearLabel(e.year)} · ${e.attraction.name}`,onclick:()=>document.getElementById(`event-${e.index}`)?.scrollIntoView({behavior:reduce?'auto':'smooth',block:'center'})});dot.style.left=`${span?(e.year-timeline.min)/span*100:50}%`;return dot;});
 const ruler=h('div',{class:'timeline-ruler'},h('div',{class:'ruler-track'},...dots),h('div',{class:'ruler-ends'},h('span',{},yearLabel(timeline.min)),h('span',{},yearLabel(timeline.max))),h('p',{class:'small timeline-legend'},h('span',{class:'ruler-key seen'}),'Visited',h('span',{class:'ruler-key today'}),'Today',h('span',{class:'ruler-key ahead'}),'Coming up'));
 const sites=new Set(timeline.events.map(e=>e.attraction.id)).size,chip={seen:'Visited',today:'Today',ahead:'Coming up'};
 const eras=timeline.bands.map(band=>h('section',{class:'era'},h('h2',{class:'era-heading'},band.label),h('ol',{class:'history-timeline'},...band.events.map(e=>h('li',{class:`history-event ${e.status}`,id:`event-${e.index}`},h('div',{class:'history-date'},e.label||yearLabel(e.year),h('span',{class:`visit-chip ${e.status}`},chip[e.status])),h('div',{},link(`${e.attraction.name} · Day ${dayNumber(trip,e.day.id)}`,attrHref(entry.id,e.day.id,e.attraction.id),{class:'history-site'}),h('h3',{},e.title),guideParagraph(trip,e.text)))))));
 main.replaceChildren(...[tabs,titleBlock('Timeline',`${timeline.events.length} milestones across ${sites} ${sites===1?'site':'sites'}`),ruler,...eras].filter(Boolean));
}
const categoryLabels={attraction:'Attraction',dining:'Dining',neighborhood:'Neighborhood'};
function placeCategory(entry,day){const categories=Object.keys(categoryLabels).filter(c=>day.attractions.some(a=>(a.category||'attraction')===c)),key=`${entry.id}/${day.id}`,saved=placeCategories.get(key);return {categories,key,selected:categories.includes(saved)?saved:categories[0]};}
function renderDay(entry,trip,day){
 const destination=trip.guideType==='destination',{categories,key,selected}=placeCategory(entry,day);
 const items=destination&&categories.length>1?day.attractions.filter(a=>(a.category||'attraction')===selected):day.attractions;
 const tabs=destination&&categories.length>1?h('div',{class:'segmented country-tabs place-category-tabs','aria-label':'Place category'},...categories.map(c=>h('button',{type:'button',class:c===selected?'active':'','aria-pressed':c===selected,onclick:()=>{placeCategories.set(key,c);renderDay(entry,trip,day);}},categoryLabels[c]))):null;
 main.replaceChildren(...[back(displayTripName(entry.meta),tripHref(entry.id)),titleBlock(dayTitle(trip,day),destination?`${day.attractions.length} ${day.attractions.length===1?'entry':'entries'}`:dateLabel(day.date,{weekday:'long',month:'long',day:'numeric',year:'numeric'}),null,'editorial-meta'),tabs,h('div',{class:'attraction-grid'},...items.map(a=>h('article',{class:'attraction-card'},link([image(a.photos[0]?.url,'',a.photos.length?'':'placeholder'),h('div',{class:'attraction-body'},h('h2',{},a.name),h('p',{},destination?(a.neighborhood||a.location):(a.visitTime||a.location)))],attrHref(entry.id,day.id,a.id),{class:'attraction-link',...photoTarget(entry,day,a)}))))].filter(Boolean));
}
function historyContextStrip(entry,context){
 const stops=context.map(event=>{
  const contents=[h('span',{class:'history-context-dot'}),h('strong',{},event.attraction.name),h('span',{},event.label||yearLabel(event.year))];
  const item=event.current?h('span',{class:'history-context-link'},contents):link(contents,attrHref(entry.id,event.day.id,event.attraction.id),{class:'history-context-link'});
  return h('li',{class:`history-context-stop${event.current?' current':''}`},item);
 });
 return h('section',{class:'history-context','aria-labelledby':'historyContextTitle'},h('h2',{id:'historyContextTitle'},'Historical context'),h('div',{class:'history-context-scroll'},h('ol',{class:'history-context-track'},...stops)));
}
function renderAttraction(entry,trip,day,a,keepComparisons=false){const destination=trip.guideType==='destination',articleKey=`${entry.id}/${day.id}/${a.id}`;if(destination)placeCategories.set(`${entry.id}/${day.id}`,a.category||'attraction');const article=h('article',{class:'article','data-article-key':articleKey},back(destination?day.title:`Day ${dayNumber(trip,day.id)}`,dayHref(entry.id,day.id)),h('p',{class:'eyebrow'},destination?`${day.title} · ${categoryLabels[a.category||'attraction']}`:dateLabel(day.date,{month:'short',day:'numeric'})+(a.visitTime?` · ${a.visitTime}`:'')),h('h1',{},a.name),(a.neighborhood||a.location)?h('p',{class:'article-location'},a.neighborhood||a.location):null);
 if(a.photos.length)article.append(h('div',{class:'photo-gallery','aria-label':'Attraction photos'},...a.photos.map((p,index)=>h('button',{class:'photo-tile',type:'button','aria-label':`View photo ${index+1} of ${a.name}`,...photoTarget(entry,day,a,index),onclick:()=>{photoContext={tripId:entry.id,dayId:day.id,attractionId:a.id};photoList=a.photos.map(photo=>({...photo,alt:a.name}));photoIndex=index;showPhoto();showDialog($('photoDialog'));}},image(p.url,a.name)))));
 const context=destination?[]:historyContext(trip,a.id);if(context.length)article.append(historyContextStrip(entry,context));
 const details=h('section',{id:'attractionDetails',role:'tabpanel','aria-labelledby':'detailsTab'});
 if(a.facts.length)details.append(h('dl',{class:'facts'},...a.facts.map(f=>h('div',{class:'fact'},h('dt',{},f.label),h('dd',{},guideText(trip,f.value))))));
 if(a.notice?.length)details.append(h('section',{class:'notice-checklist'},h('h2',{},'Three things to notice'),h('ul',{},...a.notice.map(item=>h('li',{},h('span',{'aria-hidden':'true'},'✓'),h('span',{},guideText(trip,item)))))));
 details.append(h('section',{class:'guide-text','aria-label':'Quick summary'},h('h2',{},'At a glance'),...a.summary.map(p=>guideParagraph(trip,p))));
 const timeline=historyTimeline(trip,a.id);if(timeline.length)details.append(h('section',{class:'history-section guide-text'},h('h2',{},'History timeline'),timeline.some(event=>!event.current)?h('p',{class:'small'},'This site alongside earlier places discussed in Comparisons.'):null,h('ol',{class:'history-timeline'},...timeline.map(event=>h('li',{class:event.current?'history-event current':'history-event'},h('span',{class:'history-date'},event.label),h('div',{},event.current?h('span',{class:'history-site'},a.name):link(event.attraction.name,attrHref(entry.id,event.day.id,event.attraction.id),{class:'history-site'}),h('h3',{},event.title),event.text?guideParagraph(trip,event.text):null))))));
 if(a.originality?.length)details.append(h('section',{class:'originality-section guide-text'},h('h2',{},'What’s original?'),...a.originality.map(p=>guideParagraph(trip,p))));
 if(a.sections.length){const moreDetails=h('section',{id:'moreDetail',class:'guide-text hidden'},...a.sections.map(s=>h('section',{},h('h2',{},s.heading),...s.paragraphs.map(p=>guideParagraph(trip,p)))));const more=h('button',{type:'button',class:'button read-more','aria-expanded':'false','aria-controls':'moreDetail',onclick:()=>{const open=moreDetails.classList.contains('hidden');moreDetails.classList.toggle('hidden',!open);more.setAttribute('aria-expanded',String(open));more.textContent=open?'Show less':'Read more';}},'Read more');details.append(more,moreDetails);}
 const sources=h('section',{class:'sources'},h('h2',{},'Further reading'));if(a.wikipediaUrl)sources.append(external('Read on Wikipedia ↗',a.wikipediaUrl));if(a.sources.length)sources.append(h('ul',{},...a.sources.map(s=>h('li',{},external(s.title,s.url)))));if(a.researchedAt)sources.append(h('p',{class:'small'},`Researched ${dateLabel(a.researchedAt)}. Practical details may change.`));
 details.append(sources);
 const all=destination?day.attractions.filter(other=>(other.category||'attraction')===(a.category||'attraction')).map(attraction=>({day,attraction})):attractions(trip),index=all.findIndex(item=>item.attraction.id===a.id);
 const comparisons=h('section',{id:'attractionComparisons',class:'hidden',role:'tabpanel','aria-labelledby':'comparisonsTab'});
 const validComparisons=(a.comparisons||[]).map(c=>({...c,target:all.slice(0,index).find(item=>item.attraction.id===c.attractionId)})).filter(c=>c.target);
 comparisons.append(h('p',{class:'small comparison-intro'},'Connections to places earlier in your itinerary.'));
 if(validComparisons.length)comparisons.append(...validComparisons.map(c=>h('section',{class:'panel guide-text comparison'},h('h2',{},`Compared with ${c.target.attraction.name}`),h('p',{class:'small'},dateLabel(c.target.day.date)),...c.paragraphs.map(p=>guideParagraph(trip,p)),link(`Revisit ${c.target.attraction.name}`,attrHref(entry.id,c.target.day.id,c.target.attraction.id)))));

 const tabs=h('div',{class:'segmented attraction-tabs',role:'tablist','aria-label':'Attraction information'});
 function activateTab(kind){for(const tab of tabs.children){const active=tab.id===`${kind}Tab`;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;}details.classList.toggle('hidden',kind!=='details');comparisons.classList.toggle('hidden',kind!=='comparisons');}
 for(const [kind,label,panel] of [['details','Details','attractionDetails'],['comparisons','Comparisons','attractionComparisons']])tabs.append(h('button',{id:`${kind}Tab`,type:'button',role:'tab','aria-controls':panel,'aria-selected':kind==='details',tabindex:kind==='details'?0:-1,class:kind==='details'?'active':'',onclick:()=>activateTab(kind)},label));
 tabs.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?tabs.firstChild:event.key==='End'?tabs.lastChild:event.target===tabs.firstChild?tabs.lastChild:tabs.firstChild;next.click();next.focus();}});
 if(validComparisons.length){if(keepComparisons)activateTab('comparisons');article.append(tabs,details,comparisons);}else{details.removeAttribute('role');details.removeAttribute('aria-labelledby');article.append(details);}
 const nav=h('nav',{class:'article-navigation','aria-label':'Attraction navigation'});if(index>0){const p=all[index-1];nav.append(link(`← ${p.attraction.name}`,attrHref(entry.id,p.day.id,p.attraction.id),{class:'button ghost'}));}if(index<all.length-1){const n=all[index+1];nav.append(link(`${n.attraction.name} →`,attrHref(entry.id,n.day.id,n.attraction.id),{class:'button ghost'}));}article.append(nav);main.replaceChildren(article);applyAttractionBackground(article,a.photos[0]);}
function resetAttractionBackground(){document.body.classList.remove('attraction-view','trip-detail-view','wildlife-pair-view');document.body.style.removeProperty('--attraction-bg');document.body.style.removeProperty('--trip-header-image');syncThemeColor();}
async function applyAttractionBackground(article,photo){document.body.classList.add('attraction-view');const light=document.documentElement.dataset.theme==='light';if(light)return;const color=await photoBackground(photo?.thumbnailUrl||photo?.url,1.2);if(color&&article.isConnected&&document.body.classList.contains('attraction-view')&&document.documentElement.dataset.theme!=='light')document.body.style.setProperty('--attraction-bg',color);}
function showPhoto(){const p=photoList[photoIndex],wildlife=photoContext?.kind==='wildlife',multiple=photoList.length>1,coverUpdate=wildlife&&uploadConfigured();$('largePhoto').src=p.url;$('largePhoto').alt=p.alt||`Photo ${photoIndex+1}`;$('photoNavigation').classList.toggle('hidden',!multiple&&!coverUpdate);$('replacePhoto').classList.toggle('hidden',!photoContext||wildlife||!uploadConfigured());$('wildlifeCoverPhoto').classList.toggle('hidden',!coverUpdate);$('previousPhoto').classList.toggle('hidden',!multiple);$('nextPhoto').classList.toggle('hidden',!multiple);$('photoDialog').querySelector('.photo-stage').scrollTop=0;$('previousPhoto').disabled=!multiple;$('nextPhoto').disabled=!multiple;}
function stepPhoto(n){photoIndex=(photoIndex+n+photoList.length)%photoList.length;showPhoto();}
$('previousPhoto').onclick=()=>stepPhoto(-1);$('nextPhoto').onclick=()=>stepPhoto(1);$('closePhoto').onclick=()=>$('photoDialog').close();
$('replacePhoto').onclick=()=>{if(photoContext&&!busyPhoto)$('replacementFile').click();};
$('wildlifeCoverPhoto').onclick=()=>{if(photoContext?.kind==='wildlife'&&!busyPhoto)$('replacementFile').click();};
$('replacementFile').addEventListener('change',()=>{const file=$('replacementFile').files[0];$('replacementFile').value='';if(!file||!photoContext)return;if(photoContext.kind==='wildlife')replaceWildlifePhoto(photoContext.entry,photoContext.species,file);else replaceAttractionPhoto(photoContext,photoIndex,file);});
let touchStart; $('photoDialog').addEventListener('touchstart',e=>{touchStart={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};},{passive:true});$('photoDialog').addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)stepPhoto(dx>0?-1:1);touchStart=null;},{passive:true});document.addEventListener('keydown',e=>{if($('photoDialog').open && ['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();stepPhoto(e.key==='ArrowLeft'?-1:1);}});
async function replaceAttractionPhoto(context,index,file){
 if(busyPhoto)return;if(!navigator.onLine)return notice('Connect to the internet to replace a photo.');const entry=state.entries.get(context.tripId);if(!entry)return;busyPhoto=true;notice('Preparing and uploading photo…');
 let token,uploaded;
 try{const trip=applyPhotoOverrides(await ensureTrip(entry),state.overrides),day=trip.days.find(value=>value.id===context.dayId),attraction=day?.attractions.find(value=>value.id===context.attractionId);if(!attraction)throw new Error('This attraction is no longer available.');token=await cloud.authToken();uploaded=await uploadAttractionPhoto(file,context,token);const photos=[...attraction.photos],old=photos[index];photos[index]=uploaded;const value=normalizePhotoOverride({id:photoOverrideId(context.tripId,context.attractionId),tripId:context.tripId,attractionId:context.attractionId,photos,updatedAt:Date.now()});await cloud.savePhotoOverride(value);state.overrides.set(value.id,value);await store.put('overrides',value);if(old?.publicId)destroyAttractionPhotos([old.publicId],token);if($('photoDialog').open)$('photoDialog').close();const y=scrollY;await renderRoute();requestAnimationFrame(()=>scrollTo(0,y));notice('Photo replaced. Update the trip download to use it offline.');}
 catch(error){if(uploaded?.publicId&&token)destroyAttractionPhotos([uploaded.publicId],token);notice(error.message||'The photo could not be replaced.');}finally{busyPhoto=false;}
}
const desktopDrop=matchMedia('(hover:hover) and (pointer:fine)');let dropTarget;
main.addEventListener('dragover',event=>{const target=event.target.closest('[data-photo-attraction]');if(!desktopDrop.matches||!uploadConfigured()||!target)return;event.preventDefault();event.dataTransfer.dropEffect='copy';if(dropTarget!==target){dropTarget?.classList.remove('photo-drop-active');dropTarget=target;target.classList.add('photo-drop-active');}});
main.addEventListener('dragleave',event=>{if(dropTarget&&!dropTarget.contains(event.relatedTarget)){dropTarget.classList.remove('photo-drop-active');dropTarget=null;}});
main.addEventListener('drop',event=>{const target=event.target.closest('[data-photo-attraction]'),file=event.dataTransfer?.files?.[0];dropTarget?.classList.remove('photo-drop-active');dropTarget=null;if(!desktopDrop.matches||!target||!file)return;event.preventDefault();replaceAttractionPhoto({tripId:target.dataset.photoTrip,dayId:target.dataset.photoDay,attractionId:target.dataset.photoAttraction},Number(target.dataset.photoIndex)||0,file);});
function renderSettings(){
 const theme=document.documentElement.dataset.theme||'dark',entry=state.entries.get(state.selectedId),destination=entry?.meta.guideType==='destination',fieldGuide=entry?.meta.guideType==='wildlife',noun=fieldGuide?'field guide':destination?'guide':'trip';
 const appearance=h('section',{class:'panel'},h('h2',{},'Appearance'),h('p',{},'Choose light or dark colors.'),h('div',{class:'toolbar'},...['light','dark'].map(t=>h('button',{type:'button',class:`button ${t===theme?'primary':''}`,'aria-pressed':t===theme,onclick:()=>{applyTheme(t);renderSettings();}},t==='light'?'Light':'Dark'))));
 const account=h('section',{class:'panel'},h('h2',{},'Account'),h('p',{},state.user.email||'Signed in with Google'),h('p',{class:'small',id:'syncStatus'},state.status),button('Sign out',signOut));
 const downloads=h('section',{class:'panel full'},h('h2',{},'Offline downloads'),h('p',{},'Downloads are saved on this device. Removing one keeps the guide in your shared collection.'),h('div',{id:'storageSummary',class:'storage-summary'}),h('div',{id:'downloadList'}),h('div',{id:'storageActions',class:'storage-actions'}));
 const imports=h('section',{class:'panel'},h('h2',{},'Import a guidebook'),h('p',{},'Import a dated trip, a general destination guide, or a wildlife field guide for a local area.'),button('Import guidebook',openImport,true),link('Template & instructions','setup.html#import',{class:'setup-link'}));
 const manage=entry?h('section',{class:'panel'},h('h2',{},`Selected ${noun}`),h('p',{},displayTripName(entry.meta)),downloadStatus(entry),(entry.trip||state.downloads.get(entry.id)?.revision===entry.revision)?h('p',{class:'small guide-summary'},guideSummary(entry.trip||state.downloads.get(entry.id).trip)):null,h('div',{class:'toolbar'},button(entry.archived?`Restore ${noun}`:`Archive ${noun}`,()=>archive(entry)),entry.archived?h('button',{type:'button',class:'button danger',disabled:deletesRunning.has(entry.id),onclick:()=>deleteArchivedTrip(entry)},deletesRunning.has(entry.id)?'Deleting…':'Delete'):null,state.downloads.has(entry.id)?null:button('Download',()=>startDownload(entry.id)))):null;
 const sync=h('section',{class:'panel'},h('h2',{},'About Carrots'),h('p',{},'Your shared travel and wildlife guide.'),h('p',{class:'small'},'Version 3.2.0 · Built for the places you visit.'),link('Setup guide','setup.html'),h('div',{id:'conflicts'}));
 main.replaceChildren(h('div',{class:'settings-grid'},appearance,account,manage,downloads,imports,sync));patchDownloads();patchConflicts();
}
function patchDownloads(){const list=$('downloadList');if(!list)return;list.replaceChildren();const existing=new Set();for(const d of [...state.downloads.values()].sort((a,b)=>a.name.localeCompare(b.name))){existing.add(d.id);const e=state.entries.get(d.id),current=e&&e.revision===d.revision&&(d.photoRevision||0)===guideAssetRevision(d.id),partial=d.partial&&current;list.append(h('div',{class:'download-row',id:`download-${d.id}`},h('div',{},h('h3',{},displayTripName(d)),h('p',{},`${sizeLabel(d.bytes)} · ${d.partial?`${d.imageCount} of ${d.photoTotal} photos`:`${d.imageCount} images`} · Saved ${dateLabel(new Date(d.downloadedAt).toISOString().slice(0,10))}`),partial?h('p',{class:'status warning'},'Partly saved. Continue when your connection is better.'):null,e&&!current?h('p',{class:'status warning'},'A newer guide or replacement photo is available'):null),h('div',{class:'toolbar'},partial?button('Continue',()=>startDownload(d.id,true),true):e?button('Update',()=>startDownload(d.id,true)):null,button('Remove',()=>removeDownload(d.id)))));}
 for(const [id,running] of downloadsRunning){list.append(h('div',{class:'progress-wrap',id:`progress-${id}`},h('div',{class:'progress-head'},h('p',{},displayTripName(state.entries.get(id)?.meta)||'Trip'),button('Cancel',()=>running.controller.abort())),h('p',{class:'small',id:`progressText-${id}`},'Preparing…'),h('progress',{id:`progressBar-${id}`,max:1,value:0})));if(running.progress)showProgress(id,running.progress);}
 if(!existing.size&&!downloadsRunning.size)list.append(h('p',{class:'small'},'No guidebooks downloaded yet. Use Download on a trip or destination guide to save it here.'));patchStorage();}
function patchConflicts(){const box=$('conflicts');if(!box)return;box.replaceChildren(...[...state.outbox.values()].filter(o=>o.conflict).map(o=>h('div',{class:'conflict-row'},h('h3',{},'Sync conflict'),h('p',{},`${displayTripName(state.entries.get(o.id)?.meta)||'A trip'} was changed on another device. Your imported file remains the source copy.`),button('Use synced version',()=>resolveConflict(o)))));}
async function persist(entry){const pending=state.outbox.has(entry.id);await store.put('trips',{...entry,trip:pending?entry.trip:null});}
async function archive(entry){entry=state.entries.get(entry.id);if(!entry)return;const noun=entry.meta.guideType==='wildlife'?'field guide':entry.meta.guideType==='destination'?'guide':'trip';if(state.outbox.has(entry.id)){notice(`Sync this ${noun} before changing its archive status.`);return;}const previousRevision=entry.archiveRevision,previousArchived=entry.archived;entry.archived=!entry.archived;entry.archiveRevision=uid();const op={id:entry.id,type:'archive',expectedRevision:entry.revision,expectedArchiveRevision:previousRevision,previousArchived};state.outbox.set(entry.id,op);try{await store.change([{store:'trips',value:{...entry,trip:null}},{store:'outbox',value:op}]);patchTrips();notice(entry.archived?`${destinationLabel(entry.meta)} archived.`:`${destinationLabel(entry.meta)} restored.`);flush();}catch(error){state.outbox.delete(entry.id);entry.archived=previousArchived;entry.archiveRevision=previousRevision;notice('Could not save this change on your device.');}}
const destinationLabel=meta=>meta.guideType==='destination'?'Guide':meta.guideType==='wildlife'?'Field guide':'Trip';
function guideSummary(trip){const sites=attractions(trip),wildlife=trip.wildlife?`${trip.wildlife.species.filter(s=>s.kind==='flora').length} plants · ${trip.wildlife.species.filter(s=>s.kind==='fauna').length} animals`:'';if(trip.guideType==='wildlife')return `${trip.wildlife.areas.length} ${trip.wildlife.areas.length===1?'area':'areas'} · ${wildlife}`;const common=`${sites.reduce((n,{attraction:a})=>n+(a.notice||[]).length,0)} things to notice · ${(trip.glossary||[]).length} glossary terms · ${sites.filter(({attraction:a})=>a.history?.length).length} timelines · ${sites.filter(({attraction:a})=>a.originality?.length).length} originality notes${trip.customs?.guides.length?` · ${trip.customs.guides.length} customs ${trip.customs.guides.length===1?'guide':'guides'}`:''}${wildlife?` · ${wildlife}`:''}`;return trip.guideType==='destination'?`${trip.days.length} places · ${sites.length} entries · ${common}`:`${sites.reduce((n,{attraction:a})=>n+(a.comparisons||[]).length,0)} comparisons · ${common}`;}
function openImport(){if(!state.user)return;importTrips=[];$('importPreview').replaceChildren();$('importError').textContent='';$('importFile').value='';$('confirmImport').disabled=true;showDialog($('importDialog'));}
$('importFile').addEventListener('change',async()=>{
 const file=$('importFile').files[0];$('confirmImport').disabled=true;$('importPreview').replaceChildren();$('importError').textContent='';importTrips=[];if(!file)return;
 try{
  if(file.size>MAX_FILE)throw new Error('The file is larger than 12 MB.');const epoch=state.epoch,trips=parseImport(await file.text());if(epoch!==state.epoch||!$('importDialog').open)return;importTrips=trips;
  for(const trip of trips){
   const destination=trip.guideType==='destination',fieldGuide=trip.guideType==='wildlife',matches=[...state.entries.values()].filter(e=>e.id===trip.id||(e.meta.name.toLocaleLowerCase()===trip.name.toLocaleLowerCase()&&e.meta.guideType===trip.guideType&&(destination||fieldGuide||e.meta.year===trip.year)));
   const select=h('select',{'data-import-id':trip.id,'aria-label':`Import action for ${displayTripName(trip)}`},h('option',{value:'new'},matches.length?'Import as a new guidebook':'Import guidebook'));
   for(const e of matches)select.append(h('option',{value:e.id},`Replace ${displayTripName(e.meta)}${e.archived?' (archived)':''}`));
   const description=fieldGuide?`${trip.wildlife.areas.length} ${trip.wildlife.areas.length===1?'area':'areas'} · ${trip.wildlife.species.length} species`:destination?`${trip.days.length} places · ${attractions(trip).length} entries`:`${dateLabel(trip.startDate)} – ${dateLabel(trip.endDate)} · ${trip.days.length} days · ${attractions(trip).length} attractions`;
   $('importPreview').append(h('div',{class:'import-row'},h('h3',{},displayTripName(trip)),h('p',{},description),h('p',{class:'small guide-summary'},guideSummary(trip)),select));
  }
  $('confirmImport').disabled=false;
 }catch(error){$('importError').textContent=error.message;}
});
$('confirmImport').onclick=async()=>{if(busyImport||!importTrips.length)return;busyImport=true;$('confirmImport').disabled=true;$('importError').textContent='';const epoch=state.epoch;try{const selected=[...$('importPreview').querySelectorAll('select')].map(s=>s.value).filter(v=>v!=='new');if(new Set(selected).size!==selected.length)throw new Error('Choose a different replacement trip for each import.');const operations=[],created=[];
 for(const trip of importTrips){const choice=[...$('importPreview').querySelectorAll('select')].find(s=>s.dataset.importId===trip.id).value;const old=choice==='new'?null:state.entries.get(choice);if(old&&state.outbox.has(old.id))throw new Error('A replacement trip has an unsynced change. Sync it first.');const newId=old?.id||(!state.entries.has(trip.id)?trip.id:uid());const nextTrip={...trip,id:newId};const entry={id:newId,trip:nextTrip,meta:tripMeta(nextTrip),revision:uid(),archiveRevision:uid(),archived:old?.archived||false};const op={id:newId,type:'import',expectedRevision:old?.revision||null};operations.push({store:'trips',value:entry},{store:'outbox',value:op});created.push({entry,op});}
 if(epoch!==state.epoch||!state.user)throw new Error('Sign in again before importing.');await store.change(operations);if(epoch!==state.epoch)return;for(const {entry,op} of created){state.entries.set(entry.id,entry);state.outbox.set(entry.id,op);}busyImport=false;$('importDialog').close('imported');notice(`${created.length===1?'Guidebook':'Guidebooks'} imported${navigator.onLine?'.':' and saved locally. Sync will resume online.'}`);state.selectedId=defaultTripId(created.map(c=>c.entry));state.selectionExplicit=true;location.hash=tripHref(state.selectedId).slice(1);renderRoute();flush();
 }catch(error){$('importError').textContent=error.message;}finally{busyImport=false;$('confirmImport').disabled=false;}};
async function startDownload(id,force=false){const entry=state.entries.get(id);if(!entry)return;if(downloadsRunning.has(id)){location.hash='/settings';renderSettings();return;}if(state.downloads.has(id)&&!force){location.hash='/settings';renderSettings();return;}if(!navigator.onLine){notice('Connect to the internet to download this guide.');return;}const controller=new AbortController(),epoch=state.epoch;downloadsRunning.set(id,{controller});location.hash='/settings';renderSettings();try{const trip=applyWildlifeRecords(applyPhotoOverrides(await ensureTrip(entry),state.overrides),state.wildlifeRecords),photoRevision=guideAssetRevision(id);controller.signal.throwIfAborted();if(epoch!==state.epoch)throw new Error('CANCELLED');const previous=state.downloads.get(id),d=await downloadTrip({...entry,trip},p=>{const running=downloadsRunning.get(id);if(running)running.progress=p;showProgress(id,p);},controller.signal,{resume:previous?.partial?previous:null,photoRevision});if(epoch!==state.epoch||!state.entries.has(id)){await deleteDownload(id);return;}state.downloads.set(id,d);await navigator.storage?.persist?.();notice(d.partial?`Saved ${d.imageCount} of ${d.photoTotal} photos. Continue when your connection improves.`:'Guide ready for offline reading.');}catch(error){if(epoch===state.epoch)notice(controller.signal.aborted?'Download cancelled.':error.message);}finally{downloadsRunning.delete(id);if(route().kind==='settings')patchDownloads();}}
let storageJob=0;
async function patchStorage(){
 const summary=$('storageSummary'),actions=$('storageActions');if(!summary||!actions)return;
 const job=++storageJob;let report;
 try{report=await storageReport([...state.downloads.values()]);}catch{return;}
 if(job!==storageJob||!$('storageSummary'))return;
 summary.replaceChildren(h('p',{class:'small'},report.usage==null?'Storage use is not available in this browser.':`Carrots is using ${sizeLabel(report.usage)} on this device${report.quota?` of ${sizeLabel(report.quota)} available`:''}.`));
 for(const t of report.trips){const row=$(`download-${t.id}`)?.firstElementChild;if(!row)continue;row.querySelector('.photo-details')?.remove();row.append(h('details',{class:'photo-details'},h('summary',{},`Photos saved: ${t.cached} of ${t.total}`),h('ul',{},...t.attractions.map(a=>h('li',{class:a.cached===a.total?'full':a.cached?'some':'none'},h('span',{},a.name),h('span',{class:'small'},`${a.cached} of ${a.total}`))))));}
 const archived=new Set([...state.entries.values()].filter(e=>e.archived).map(e=>e.id)),archivedDownloads=[...state.downloads.values()].filter(d=>archived.has(d.id));
 const reclaimable=report.orphanBytes+archivedDownloads.reduce((sum,d)=>sum+d.bytes,0),busy=downloadsRunning.size>0,anything=report.orphanCount>0||archivedDownloads.length>0;
 actions.replaceChildren(h('button',{type:'button',class:'button',disabled:busy||!anything,onclick:()=>freeSpace(archived)},busy?'Free up space after downloads finish':anything?`Free up space (${sizeLabel(reclaimable)})`:'Nothing to free up'),h('p',{class:'small'},'Removes saved photos of archived trips and leftover partial downloads. Your other downloads stay.'));
}
async function freeSpace(archived){
 if(downloadsRunning.size)return notice('Wait for downloads to finish.');
 if(!await ask('Free up space?','This removes the saved photos of archived guidebooks and any leftover partial downloads from this device. Your other downloads and shared guidebooks stay.','Free up'))return;
 try{const freed=await freeUpSpace([...state.downloads.values()],archived);for(const id of archived){state.downloads.delete(id);const e=state.entries.get(id);if(e&&!state.outbox.has(id))e.trip=null;}patchDownloads();notice(freed>0?`Freed ${sizeLabel(freed)}.`:'Nothing to free up.');}
 catch{notice('Could not free up space. Try again.');}
}
function showProgress(id,p){const bar=$(`progressBar-${id}`),label=$(`progressText-${id}`),destination=state.entries.get(id)?.meta.guideType==='destination';if(bar){bar.max=Math.max(1,p.total);bar.value=p.done?bar.max:p.completed;}if(label)label.textContent=`${p.completed} of ${p.total} images · ${sizeLabel(p.bytes)}${p.day?` · ${destination?'Place':'Day'} ${p.day}`:''}${p.weak&&!destination?' · Slow connection, saving upcoming days first':''}`;}
async function removeDownload(id){if(downloadsRunning.has(id)){notice('Cancel or finish the download before removing it.');return;}if(!await ask('Remove this download?','The local guide and downloaded images will be removed. The shared guidebook remains available online.'))return;try{await deleteDownload(id);state.downloads.delete(id);const e=state.entries.get(id);if(e&&!state.outbox.has(id))e.trip=null;patchDownloads();notice('Download removed from this device.');}catch{notice('Could not remove the download. Try again.');}}
async function dropTrip(id){downloadsRunning.get(id)?.controller.abort();state.entries.delete(id);state.downloads.delete(id);state.outbox.delete(id);customsCountries.delete(id);const operations=[{store:'trips',type:'delete',id},{store:'outbox',type:'delete',id}];for(const value of [...state.overrides.values()])if(value.tripId===id){state.overrides.delete(value.id);operations.push({store:'overrides',type:'delete',id:value.id});}for(const key of placeCategories.keys())if(key.startsWith(`${id}/`))placeCategories.delete(key);await store.change(operations);await deleteDownload(id);}
async function deleteArchivedTrip(entry){const id=entry.id;entry=state.entries.get(id);if(!entry?.archived||deletesRunning.has(id))return;const noun=entry.meta.guideType==='destination'?'guide':'trip';if(!navigator.onLine)return notice(`Connect to the internet to delete this ${noun}.`);if(state.outbox.has(id))return notice(`Sync this ${noun} before deleting it.`);if(downloadsRunning.has(id))return notice(`Finish or cancel the download before deleting this ${noun}.`);const epoch=state.epoch,revision=entry.revision,archiveRevision=entry.archiveRevision;if(!await ask(`Delete ${displayTripName(entry.meta)}?`,`This removes the ${noun} from your shared collection and removes its downloads as devices sync. You can import the original JSON again.`,'Delete'))return;if(epoch!==state.epoch||!state.user)return;entry=state.entries.get(id);if(!entry?.archived||entry.revision!==revision||entry.archiveRevision!==archiveRevision||state.outbox.has(id)){renderSettings();notice(`This ${noun} changed. Review it before deleting.`);return;}deletesRunning.add(id);renderSettings();try{const replacements=[...state.overrides.values()].filter(value=>value.tripId===id),token=replacements.length?await cloud.authToken():null;await cloud.deleteArchived(entry,()=>epoch!==state.epoch||!state.user);if(epoch!==state.epoch)return;await Promise.allSettled(replacements.map(value=>cloud.deletePhotoOverride(value.id)));if(token)destroyAttractionPhotos(replacements.flatMap(value=>value.photos.map(photo=>photo.publicId).filter(Boolean)),token);await dropTrip(id);patchTrips();notice(`${destinationLabel(entry.meta)} deleted.`);}catch(error){if(epoch!==state.epoch)return;notice(error.message==='CONFLICT'?`This ${noun} changed on another device. Sync it before deleting.`:`Could not delete the ${noun}. Try again when connected.`);}finally{deletesRunning.delete(id);if(state.user&&route().kind==='settings')renderSettings();}}
async function flush(){if(syncJob){syncAgain=true;return syncJob;}if(!state.user||!navigator.onLine)return;const epoch=state.epoch;syncJob=(async()=>{for(const op of [...state.outbox.values()]){if(epoch!==state.epoch||!navigator.onLine)return;if(op.conflict)continue;const e=state.entries.get(op.id);if(!e)continue;status('Syncing…');try{const cancelled=()=>epoch!==state.epoch||!state.user;if(op.type==='import')await cloud.saveImport(e,op.expectedRevision,cancelled);else await cloud.saveArchive(e,op.expectedRevision,op.expectedArchiveRevision,cancelled);if(cancelled())return;if(state.outbox.get(op.id)!==op)continue;await store.remove('outbox',op.id);if(cancelled())return;state.outbox.delete(op.id);await persist(e);patchTrips();}catch(error){if(epoch!==state.epoch)return;if(error.message==='CONFLICT'){op.conflict=true;await store.put('outbox',op);notice('A trip changed on another device. Review the conflict in Settings.');patchConflicts();}else{status('Sync paused · changes saved locally');return;}}}status(state.outbox.size?'Changes need attention':'Synced');})().finally(()=>{syncJob=null;if(syncAgain){syncAgain=false;setTimeout(flush,0);}});return syncJob;}
async function flushWildlife(){if(wildlifeSyncJob){wildlifeSyncAgain=true;return wildlifeSyncJob;}if(!state.user||!navigator.onLine)return;const epoch=state.epoch;wildlifeSyncJob=(async()=>{for(const op of [...state.wildlifeOps.values()]){if(epoch!==state.epoch||!navigator.onLine)return;const setup=wildlifeKinds[op.kind];if(!setup)continue;try{if(op.type==='delete')await cloud.deleteWildlife(setup.remote,op.docId);else await cloud.saveWildlife(setup.remote,op.value);if(epoch!==state.epoch||state.wildlifeOps.get(op.id)!==op)return;state.wildlifeOps.delete(op.id);await store.remove('wildlifeOps',op.id);}catch{status('Wildlife sync paused · changes saved locally');return;}}if(!state.outbox.size)status('Synced');})().finally(()=>{wildlifeSyncJob=null;if(wildlifeSyncAgain){wildlifeSyncAgain=false;setTimeout(flushWildlife,0);}});return wildlifeSyncJob;}
async function receiveWildlife(kind,values){if(!state.user)return;const setup=wildlifeKinds[kind],next=new Map();for(const raw of values){try{const value=setup.normalize(raw);next.set(value.id,value);}catch{}}for(const op of state.wildlifeOps.values())if(op.kind===kind){if(op.type==='delete')next.delete(op.docId);else next.set(op.docId,op.value);}state[setup.map]=next;await store.change([{store:setup.store,type:'clear'},...next.values().map(value=>({store:setup.store,value}))]);if(kind==='records')await migrateLegacyWildlifeNotes();if(route().kind==='wildlife'&&!busyPhoto)renderRoute();}
async function resolveConflict(op){if(!navigator.onLine)return notice('Connect to resolve this conflict.');if(!await ask('Use the synced version?','This replaces the unsynced local change. You can re-import your original file later.'))return;try{const meta=await cloud.remoteMeta(op.id);await store.remove('outbox',op.id);state.outbox.delete(op.id);if(meta&&!meta.deleted){const entry={id:meta.id,meta,revision:meta.revision,archiveRevision:meta.archiveRevision,archived:meta.archived,trip:null};state.entries.set(entry.id,entry);await persist(entry);}else await dropTrip(op.id);patchConflicts();patchTrips();status(state.outbox.size?'Changes need attention':'Synced');}catch(error){notice('Could not load the synced version. Try again.');}}
async function receivePhotoOverrides(values){if(!state.user)return;const next=new Map();for(const raw of values){try{const value=normalizePhotoOverride(raw);next.set(value.id,value);}catch{}}state.overrides=next;await store.change([{store:'overrides',type:'clear'},...next.values().map(value=>({store:'overrides',value}))]);if(state.selectedId&&!busyPhoto&&!document.querySelector('dialog[open]')&&['trip','day','attraction'].includes(route().kind))renderRoute();}
async function receive(metas){if(!state.user)return;const epoch=state.epoch;for(const rawMeta of metas){try{if(rawMeta?.deleted===true){const deletedId=text(rawMeta.id,100,'Trip ID',true);if(/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,99}$/.test(deletedId)&&!state.outbox.has(deletedId)){await dropTrip(deletedId);if(epoch!==state.epoch)return;}continue;}const meta=normalizeMeta(rawMeta);const id=text(meta.id,100,'Trip ID',true);if(!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,99}$/.test(id)||!Array.isArray(meta.days)||typeof meta.name!=='string'||typeof meta.revision!=='string')continue;const old=state.entries.get(id);if(state.outbox.has(id))continue;const changed=old?.revision!==meta.revision;const entry={id,meta,revision:meta.revision,archiveRevision:meta.archiveRevision,archived:meta.archived===true,trip:changed?null:old?.trip||null};state.entries.set(id,entry);await persist(entry);if(epoch!==state.epoch)return;if(state.selectionExplicit&&route().id===id&&changed&&!document.querySelector('dialog[open]')&&!$('tripSearch')?.value){renderRoute();}}catch{status('A synced guidebook could not be read.');}}
 state.loaded=true;const previous=state.selectedId;if(!state.selectionExplicit||!state.selectedId){state.selectedId=state.entries.has(initialTripId)?initialTripId:defaultTripId(state.entries.values());state.selectionExplicit=Boolean(state.selectedId);if(state.selectedId&&route().kind!=='settings'&&!(state.selectedId===initialTripId&&['day','attraction'].includes(route().kind))){const href=route().kind==='customs'?`#/customs/${state.selectedId}`:tripHref(state.selectedId);history.replaceState(null,'',href);routeKey=href;}}refreshSelector();if(previous!==state.selectedId||!route().id&&route().kind!=='settings')renderRoute();else if(route().kind==='settings'&&!document.querySelector('dialog[open]'))renderSettings();if(!state.outbox.size)status(navigator.onLine?'Synced':'Offline');}
async function authChanged(user){const epoch=++state.epoch;unsubscribe?.();unsubscribeOverrides?.();wildlifeUnsubscribers.forEach(stop=>stop());wildlifeUnsubscribers=[];unsubscribe=unsubscribeOverrides=null;if(!cloud.authorized(user)){state.user=null;downloadsRunning.forEach(r=>r.controller.abort());clearWildlifeBrowsing();placeCategories.clear();for(const key of ['entries','downloads','outbox','overrides','wildlifeRecords','wildlifeNotes','wildlifeOps'])state[key].clear();state.selectedId=null;state.selectionExplicit=false;selectorSignature='';await store.clearPrivate();if(user){status('This Google account is not authorized for Carrots.');await cloud.logout();}else if(!state.status.includes('not authorized'))status('Sign in to open your guidebooks');gate();return;}
 state.user=user;status(navigator.onLine?'Syncing…':'Offline · saved guidebooks');try{const [entries,downloads,outbox,overrides,records,notes,wildlifeOps]=await Promise.all([store.all('trips'),store.all('downloads'),store.all('outbox'),store.all('overrides'),store.all('wildlifeRecords'),store.all('wildlifeSightings'),store.all('wildlifeOps')]);if(epoch!==state.epoch)return;state.entries=new Map(entries.map(e=>[e.id,e]));state.downloads=new Map(downloads.map(e=>[e.id,e]));state.outbox=new Map(outbox.map(e=>[e.id,e]));state.wildlifeRecords=new Map(records.map(raw=>{try{const value=normalizeWildlifeRecord(raw);return [value.id,value];}catch{return [raw.id,raw];}}));state.wildlifeNotes=new Map(notes.flatMap(raw=>{try{const value=normalizeWildlifeNote(raw);return [[value.id,value]];}catch{return [];}}));state.wildlifeOps=new Map(wildlifeOps.filter(value=>wildlifeKinds[value.kind]).map(e=>[e.id,e]));for(const op of wildlifeOps)if(!wildlifeKinds[op.kind])await store.remove('wildlifeOps',op.id);await store.change([{store:'wildlifeOutings',type:'clear'},{store:'wildlifeSightings',type:'clear'},...state.wildlifeNotes.values().map(value=>({store:'wildlifeSightings',value}))]);state.overrides=new Map();for(const raw of overrides){try{const value=normalizePhotoOverride(raw);state.overrides.set(value.id,value);}catch{await store.remove('overrides',raw?.id).catch(()=>{});}}await migrateLegacyWildlifeNotes();state.loaded=true;state.selectionExplicit=Boolean(route().id&&state.entries.has(route().id));renderRoute();await removeOrphans();unsubscribe=cloud.listen(receive,error=>{status(`Sync unavailable (${error.code||'connection error'})`);notice('Your downloaded guidebooks are still available. Check the Firebase rules and connection.');});unsubscribeOverrides=cloud.listenPhotoOverrides(receivePhotoOverrides,error=>{status(`Photo sync unavailable (${error.code||'connection error'})`);});wildlifeUnsubscribers=Object.keys(wildlifeKinds).map(kind=>cloud.listenWildlife(wildlifeKinds[kind].remote,values=>receiveWildlife(kind,values),error=>status(`Wildlife sync unavailable (${error.code||'connection error'})`)));flush();flushWildlife();}catch{status('Browser storage unavailable');notice('Carrots needs browser storage to save imports and offline guidebooks.');renderRoute();}}
async function signOut(){if(!await ask('Sign out?','Downloaded trips and private local data will be removed from this device.'+(state.outbox.size||state.wildlifeOps.size?' Unsynced changes will be discarded.':'')))return;const epoch=++state.epoch;unsubscribe?.();unsubscribeOverrides?.();wildlifeUnsubscribers.forEach(stop=>stop());wildlifeUnsubscribers=[];unsubscribe=unsubscribeOverrides=null;state.user=null;downloadsRunning.forEach(r=>r.controller.abort());document.querySelectorAll('dialog[open]').forEach(d=>d.close());clearWildlifeBrowsing();placeCategories.clear();for(const key of ['entries','downloads','outbox','overrides','wildlifeRecords','wildlifeNotes','wildlifeOps'])state[key].clear();state.selectedId=null;state.selectionExplicit=false;selectorSignature='';status('Signing out…');gate();try{await cloud.logout();}catch{notice('Google sign-out needs a retry. Local guidebooks have been cleared.');}await store.clearPrivate();if(epoch<=state.epoch){status('Sign in to open your guidebooks');gate();}}
function syncThemeColor(){document.querySelector('meta[name=theme-color]').content='transparent';}
function applyTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem('glauco-theme',theme);}catch{}syncThemeColor();}
try{applyTheme(localStorage.getItem('glauco-theme')||'dark');}catch{applyTheme('dark');}
try{localStorage.removeItem('glauco-style');}catch{}
window.addEventListener('online',()=>{status('Reconnecting…');if(state.user){cloud.setNetwork(true).then(()=>{flush();flushWildlife();}).catch(()=>status('Sync unavailable'));}checkRelease();});window.addEventListener('offline',()=>{status('Offline · saved guidebooks');if(state.user)cloud.setNetwork(false).catch(()=>{});});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;let dismissed=false;try{dismissed=localStorage.getItem('glauco-install-dismissed')==='1';}catch{}if(!dismissed)$('installBanner').classList.remove('hidden');});$('installApp').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('installBanner').classList.add('hidden');};$('dismissInstall').onclick=()=>{$('installBanner').classList.add('hidden');try{localStorage.setItem('glauco-install-dismissed','1');}catch{}};
let registration,newRelease=false;const RELEASE='3.2.0';
async function checkRelease(){if(!navigator.onLine)return;try{const response=await fetch(`release.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)return;const release=await response.json();if(release.version!==RELEASE){newRelease=true;await registration?.update();$('releaseBanner').classList.remove('hidden');}}catch{}}
$('updateApp').onclick=async()=>{if(document.querySelector('dialog[open]')||downloadsRunning.size||busyImport){notice('Finish the open dialog or download before updating.');return;}if((state.outbox.size||state.wildlifeOps.size)&&navigator.onLine){await flush();await flushWildlife();}if(state.outbox.size||state.wildlifeOps.size){notice('Sync pending changes before updating.');return;}if(registration?.waiting)registration.waiting.postMessage({type:'ACTIVATE'});else if(newRelease)location.reload();};
if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').then(r=>{registration=r;if(r.waiting){newRelease=true;$('releaseBanner').classList.remove('hidden');}r.addEventListener('updatefound',()=>{const worker=r.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){newRelease=true;$('releaseBanner').classList.remove('hidden');}});});}).catch(()=>notice('Offline app support could not start. Use HTTPS and allow site storage.'));let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloading&&newRelease){reloading=true;location.reload();}});}
setTimeout(checkRelease,1800);setInterval(()=>{if(state.user&&navigator.onLine){if(state.outbox.size)flush();if(state.wildlifeOps.size)flushWildlife();}},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){checkRelease();if(state.user&&navigator.onLine){flush();flushWildlife();}}});
routeKey=location.hash||'#/trip';updateNav();scheduleToday();
if(cloud.configured()){status('Checking your account…');gate();try{cloud.startAuth(authChanged);}catch(error){status(`Firebase could not start (${error.code||'configuration error'})`);gate();}}
else{status('Firebase setup required');gate();}
