import {config} from './config.js';
import * as cloud from './firebase.js';
import * as store from './storage.js';
import {parseImport,normalizeTrip,tripMeta,attractions,uid,dateLabel,sizeLabel,MAX_FILE,text,normalizeMeta} from './model.js';
import {downloadTrip,deleteDownload,removeOrphans} from './offline.js';
const $=id=>document.getElementById(id), main=$('main');
const state={user:null,entries:new Map(),downloads:new Map(),outbox:new Map(),filter:'active',status:'Starting…',epoch:0,loaded:false};
let unsubscribe, syncJob, syncAgain=false, routeKey='', viewToken=0, importTrips=[], noticeTimer, photoList=[], photoIndex=0, busyImport=false;
const scrolls=new Map(), downloadsRunning=new Map();
const icons={book:'M4 4h6l2 2 2-2h6v16h-6l-2 2-2-2H4zM12 6v16',back:'m14 5-7 7 7 7',arrow:'m9 5 7 7-7 7',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',photo:'M3 3h18v18H3zM3 17l6-6 5 5 3-3 4 4M8 7h.01'};
function h(tag,props={},...children){const e=document.createElement(tag);for(const [k,v] of Object.entries(props)){if(v==null)continue;if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='disabled')e.disabled=v;else e.setAttribute(k,String(v));}for(const c of children.flat(Infinity))if(c!=null)e.append(c instanceof Node?c:document.createTextNode(String(c)));return e;}
function icon(name){const e=document.createElementNS('http://www.w3.org/2000/svg','svg');e.setAttribute('viewBox','0 0 24 24');e.setAttribute('aria-hidden','true');const p=document.createElementNS(e.namespaceURI,'path');p.setAttribute('d',icons[name]||icons.book);e.append(p);return e;}
function button(label,fn,primary=false){return h('button',{type:'button',class:`button ${primary?'primary':''}`,onclick:fn},label);}
function link(label,href,props={}){return h('a',{href,...props},label);}
function external(label,href){return link(label,href,{target:'_blank',rel:'noopener noreferrer'});}
function image(src,alt,cls=''){if(!src)return h('div',{class:`placeholder ${cls}`},icon('photo'));const img=h('img',{src,alt,loading:'lazy',decoding:'async',class:cls});img.addEventListener('error',()=>{img.replaceWith(h('div',{class:`placeholder ${cls}`,'aria-label':`${alt || 'Image'} unavailable`},icon('photo')));},{once:true});return img;}
function notice(message){$('notice').textContent=message;$('notice').classList.remove('hidden');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').classList.add('hidden'),6500);}
function status(message){state.status=message;$('connection').textContent=message;const text=$('syncStatus');if(text)text.textContent=message;}
function route(){const parts=(location.hash.slice(1)||'/trips').split('/').filter(Boolean);return {kind:parts[0]||'trips',id:parts[1],day:parts[2],attraction:parts[3]};}
const tripHref=id=>`#/trip/${id}`,dayHref=(id,day)=>`#/day/${id}/${day}`,attrHref=(id,day,a)=>`#/attraction/${id}/${day}/${a}`;
function back(label,href){return link([icon('back'),label],href,{class:'back-link'});}
function empty(title,message,action){return h('div',{class:'empty'},icon('book'),h('h1',{},title),h('p',{},message),action);}
function updateNav(){const settings=route().kind==='settings';document.querySelectorAll('[data-tab]').forEach(a=>{const active=(a.dataset.tab==='settings')===settings;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
function gate(){main.replaceChildren(h('section',{class:'panel auth-card'},h('a',{class:'brand',href:'#/trips'},icon('book'),'Glauco'),h('h1',{},'A guide for every stop.'),h('p',{},'Stories, details, and things to notice. Your personal guidebook, ready to take along.'),cloud.configured()?button('Sign in with Google',signIn,true):h('p',{},'Connect your Firebase project to get started.'),h('p',{class:'small',id:'gateMessage'},state.status),link(cloud.configured()?'Setup & import guide':'Set up Glauco','setup.html',{class:'setup-link'})));}
async function signIn(){if(!cloud.configured())return;try{await cloud.login();}catch(error){status(error.code==='auth/popup-blocked'?'Allow the Google sign-in popup, then try again.':`Sign-in did not finish (${error.code||'connection error'}). Check Firebase setup.`);gate();}}
async function ask(title,message){$('confirmTitle').textContent=title;$('confirmText').textContent=message;return new Promise(resolve=>{const dialog=$('confirmDialog');dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true});showDialog(dialog);});}
function showDialog(dialog){dialog.returnValue='';history.pushState({...history.state,glaucoDialog:dialog.id},'',location.href);dialog.showModal();}
for(const dialog of document.querySelectorAll('dialog')){
 dialog.addEventListener('click',event=>{if(event.target===dialog && !(dialog.id==='importDialog'&&busyImport))dialog.close('cancel');});
 dialog.addEventListener('cancel',event=>{if(dialog.id==='importDialog'&&busyImport)event.preventDefault();});
 dialog.addEventListener('close',()=>{if(history.state?.glaucoDialog===dialog.id)history.back();});
}
window.addEventListener('popstate',()=>{document.querySelectorAll('dialog[open]').forEach(d=>{if(history.state?.glaucoDialog!==d.id)d.close('cancel');});});
window.addEventListener('hashchange',()=>{const newKey=location.hash||'#/trips';if(newKey===routeKey)return;scrolls.set(routeKey,window.scrollY);routeKey=newKey;renderRoute();requestAnimationFrame(()=>window.scrollTo(0,scrolls.get(routeKey)||0));});
function sortedEntries(){return [...state.entries.values()].filter(e=>e.archived===(state.filter==='archived')).sort((a,b)=>b.meta.startDate.localeCompare(a.meta.startDate)||a.meta.name.localeCompare(b.meta.name));}
function downloadStatus(entry){const d=state.downloads.get(entry.id);if(!d)return h('span',{class:'status'},state.outbox.has(entry.id)?'Waiting to sync':'Not downloaded');const ready=d.revision===entry.revision;return h('span',{class:`status ${ready?'ready':'warning'}`},`${ready?'✓ Offline ready':'Download update available'} · ${sizeLabel(d.bytes)}`);}
function tripCard(entry){const m=entry.meta,count=m.days.reduce((sum,d)=>sum+d.attractionIds.length,0);const card=h('article',{class:'trip-card','data-id':entry.id,'data-revision':entry.revision});card.append(link([image(m.coverUrl,'','trip-cover'),h('div',{class:'trip-body'},h('h2',{class:'trip-name'},m.name),h('p',{class:'small'},`${dateLabel(m.startDate)} – ${dateLabel(m.endDate)}`),h('span',{class:'small'},`${m.days.length} days · ${count} attractions`))],tripHref(entry.id),{class:'trip-link'}));const footer=h('div',{class:'trip-footer'},downloadStatus(entry),h('div',{class:'card-actions'},button(entry.archived?'Restore':'Archive',()=>archive(entry)),button(state.downloads.has(entry.id)?'Downloads':'Download',()=>startDownload(entry.id))));card.append(footer);return card;}
function renderTrips(){const heading=h('div',{class:'page-heading'},h('div',{},h('p',{class:'eyebrow'},'YOUR PERSONAL GUIDE'),h('h1',{},'Trips'),h('p',{class:'muted'},'A little context. A closer look.')),button('+ Import',openImport,true));const tabs=h('div',{class:'segmented','aria-label':'Trip collection'},...['active','archived'].map(f=>h('button',{type:'button',class:state.filter===f?'active':'','aria-pressed':state.filter===f,onclick:()=>{state.filter=f;renderTrips();}},f==='active'?'Trips':'Archived')));main.replaceChildren(heading,tabs,h('div',{class:'trip-grid',id:'tripGrid'}));patchTrips();}
function patchTrips(){const grid=$('tripGrid');if(!grid)return;const entries=sortedEntries();if(!entries.length){grid.className='';grid.replaceChildren(empty(state.filter==='archived'?'No archived trips':'Your next trip starts here.',state.filter==='archived'?'Archived trips stay synced and can be restored anytime.':'Give ChatGPT your Lambus export, then import the Glauco trip file it prepares.',state.filter==='active'?button('Import a trip',openImport,true):null));return;}grid.className='trip-grid';grid.querySelector('.empty')?.remove();const wanted=new Set(entries.map(e=>e.id));for(const card of [...grid.children])if(!wanted.has(card.dataset.id))card.remove();for(let index=0;index<entries.length;index++){const e=entries[index];let card=[...grid.children].find(n=>n.dataset.id===e.id);const signature=`${e.revision}:${e.archiveRevision}:${e.archived}:${state.downloads.get(e.id)?.revision||''}:${state.outbox.has(e.id)}`;if(!card||card.dataset.signature!==signature){const next=tripCard(e);next.dataset.signature=signature;if(card)card.replaceWith(next);card=next;}if(grid.children[index]!==card)grid.insertBefore(card,grid.children[index]||null);}}
function titleBlock(title,subtitle,action){return h('div',{class:'page-heading'},h('div',{},h('h1',{},title),h('p',{class:'muted'},subtitle)),action);}
function visibleEntry(id){return state.entries.get(id);}
async function ensureTrip(entry){if(!navigator.onLine){const d=state.downloads.get(entry.id);if(d)return d.trip;if(state.outbox.has(entry.id)&&entry.trip)return entry.trip;throw new Error('Download this trip while online to read it without a connection.');}if(entry.trip)return entry.trip;const epoch=state.epoch,revision=entry.revision;const trip=await cloud.readRemote({...entry.meta,revision});if(epoch!==state.epoch||!state.user||state.entries.get(entry.id)?.revision!==revision)throw new Error('The trip changed. Open it again.');entry.trip=trip;return trip;}
async function renderRoute(){updateNav();const token=++viewToken;if(!state.user)return gate();const r=route();if(r.kind==='settings')return renderSettings();if(!['trip','day','attraction'].includes(r.kind))return renderTrips();const entry=visibleEntry(r.id);if(!entry){main.replaceChildren(back('Trips','#/trips'),empty(state.loaded?'Trip not found':'Syncing your trips…',state.loaded?'Return to Trips and choose a guidebook.':'Your guidebooks will appear after synchronization.'));return;}let trip;
 try{if(!entry.trip&&navigator.onLine)main.replaceChildren(back('Trips','#/trips'),empty('Opening your trip…','Loading its guidebook.'));trip=await ensureTrip(entry);}catch(error){if(token===viewToken)main.replaceChildren(back('Trips','#/trips'),empty('This trip needs a connection.',error.message,navigator.onLine?button('Try again',renderRoute):null));return;}
 if(token!==viewToken)return;
 if(r.kind==='trip')renderTrip(entry,trip);
 else {const day=trip.days.find(d=>d.id===r.day);if(!day){main.replaceChildren(back('Trip',tripHref(entry.id)),empty('Day not found','Choose another day from the trip.'));return;}if(r.kind==='day')renderDay(entry,day);else{const a=day.attractions.find(a=>a.id===r.attraction);if(a)renderAttraction(entry,trip,day,a);else main.replaceChildren(back('Day',dayHref(entry.id,day.id)),empty('Attraction not found','Choose another attraction from this day.'));}}
 main.focus({preventScroll:true});
}
function renderTrip(entry,trip){const search=h('input',{id:'tripSearch',type:'search',placeholder:'Search this trip','aria-label':'Search this trip',maxlength:150});const clear=h('button',{type:'button','aria-label':'Clear search',onclick:()=>{search.value='';search.focus();updateSearch();}},'×');const days=h('div',{id:'days',class:'days'},...trip.days.map(d=>{
 const heading=link([h('div',{},h('h2',{},d.title),h('p',{},dateLabel(d.date,{weekday:'long',month:'long',day:'numeric'}))),h('span',{class:'day-count'},`${d.attractions.length} stops`,icon('arrow'))],dayHref(entry.id,d.id),{class:'day-heading'});
 const strip=h('div',{class:'thumb-strip','aria-label':`Attractions on ${dateLabel(d.date)}`},...d.attractions.map(a=>link(image(a.photos[0]?.thumbnailUrl||a.photos[0]?.url,'',a.photos.length?'':'placeholder'),attrHref(entry.id,d.id,a.id),{class:`thumbnail ${a.photos.length?'':'placeholder'}`,'aria-label':a.name,title:a.name})));
 const card=h('article',{class:'day-card',onclick:event=>{if(!event.target.closest('a,button')&&!event.target.closest('.thumb-strip')&& !window.getSelection()?.toString())location.hash=dayHref(entry.id,d.id).slice(1);}},heading,strip);return card;
 }));const results=h('div',{id:'searchResults',class:'hidden','aria-live':'polite'});
 main.replaceChildren(back('Trips','#/trips'),titleBlock(trip.name,`${dateLabel(trip.startDate)} – ${dateLabel(trip.endDate)}`,button(state.downloads.has(entry.id)?'Downloads':'Download',()=>startDownload(entry.id))),downloadStatus(entry),h('div',{class:'search-wrap'},icon('search'),search,clear),results,days);
 if(!navigator.onLine){main.insertBefore(h('p',{class:'offline-note'},state.downloads.get(entry.id)?.revision===entry.revision?'Reading your downloaded guide offline.':'Reading the saved version of this trip. Reconnect to check for updates.'),days);}
 const searchable=attractions(trip).map(item=>({...item,text:[item.attraction.name,item.attraction.location,...item.attraction.summary,...item.attraction.facts.flatMap(f=>[f.label,f.value]),...item.attraction.sections.flatMap(s=>[s.heading,...s.paragraphs])].join(' ').toLocaleLowerCase()}));
 function updateSearch(){const query=search.value.trim().toLocaleLowerCase();days.classList.toggle('hidden',Boolean(query));results.classList.toggle('hidden',!query);if(!query){results.replaceChildren();return;}const matches=searchable.filter(a=>a.text.includes(query));results.replaceChildren(h('p',{class:'small'},`${matches.length} ${matches.length===1?'attraction':'attractions'} found`),...matches.map(({day,attraction:a})=>link([image(a.photos[0]?.thumbnailUrl,'',''),h('div',{},h('h3',{},a.name),h('p',{},`${dateLabel(day.date)} · ${day.title}`))],attrHref(entry.id,day.id,a.id),{class:'result'})));}
 search.addEventListener('input',updateSearch);
}
function renderDay(entry,day){main.replaceChildren(back(entry.meta.name,tripHref(entry.id)),titleBlock(day.title,dateLabel(day.date,{weekday:'long',month:'long',day:'numeric',year:'numeric'})),h('div',{class:'attraction-grid'},...day.attractions.map(a=>h('article',{class:'attraction-card'},link([image(a.photos[0]?.url,'',a.photos.length?'':'placeholder'),h('div',{class:'attraction-body'},h('h2',{},a.name),h('p',{},a.visitTime||a.location))],attrHref(entry.id,day.id,a.id),{class:'attraction-link'})))));}
function renderAttraction(entry,trip,day,a){const article=h('article',{class:'article'},back(day.title,dayHref(entry.id,day.id)),h('p',{class:'eyebrow'},dateLabel(day.date,{month:'short',day:'numeric'})+(a.visitTime?` · ${a.visitTime}`:'')),h('h1',{},a.name),a.location?h('p',{class:'article-location'},a.location):null);
 if(a.photos.length)article.append(h('div',{class:'photo-gallery','aria-label':'Attraction photos'},...a.photos.map((p,index)=>h('button',{class:'photo-tile',type:'button','aria-label':`View photo ${index+1}${p.caption?`: ${p.caption}`:''}`,onclick:()=>{photoList=a.photos;photoIndex=index;showPhoto();showDialog($('photoDialog'));}},image(p.url,p.caption||a.name),h('span',{},p.caption||`Photo ${index+1} of ${a.photos.length}`)))));
 if(a.facts.length)article.append(h('dl',{class:'facts'},...a.facts.map(f=>h('div',{class:'fact'},h('dt',{},f.label),h('dd',{},f.value)))));
 article.append(h('section',{class:'guide-text','aria-label':'Quick summary'},h('h2',{},'At a glance'),...a.summary.map(p=>h('p',{},p))));
 if(a.sections.length){const details=h('section',{id:'moreDetail',class:'guide-text hidden'},...a.sections.map(s=>h('section',{},h('h2',{},s.heading),...s.paragraphs.map(p=>h('p',{},p)))));const more=h('button',{type:'button',class:'button read-more','aria-expanded':'false','aria-controls':'moreDetail',onclick:()=>{const open=details.classList.contains('hidden');details.classList.toggle('hidden',!open);more.setAttribute('aria-expanded',String(open));more.textContent=open?'Show less':'Read more';}},'Read more');article.append(more,details);}
 const sources=h('section',{class:'sources'},h('h2',{},'Further reading'));if(a.wikipediaUrl)sources.append(external('Read on Wikipedia ↗',a.wikipediaUrl));if(a.sources.length)sources.append(h('ul',{},...a.sources.map(s=>h('li',{},external(s.title,s.url)))));if(a.researchedAt)sources.append(h('p',{class:'small'},`Researched ${dateLabel(a.researchedAt)}. Practical details may change.`));
 if(a.photos.length){sources.append(h('h3',{},'Photo credits'),h('ul',{},...a.photos.map(p=>h('li',{},p.creator||'Creator listed at source',p.license?` · ${p.license}`:'',p.sourceUrl?[' · ',external('Source',p.sourceUrl)]:null,p.licenseUrl?[' · ',external('License',p.licenseUrl)]:null))));}article.append(sources);
 const all=attractions(trip),index=all.findIndex(item=>item.attraction.id===a.id);const nav=h('nav',{class:'article-navigation','aria-label':'Attraction navigation'});if(index>0){const p=all[index-1];nav.append(link(`← ${p.attraction.name}`,attrHref(entry.id,p.day.id,p.attraction.id),{class:'button ghost'}));}if(index<all.length-1){const n=all[index+1];nav.append(link(`${n.attraction.name} →`,attrHref(entry.id,n.day.id,n.attraction.id),{class:'button ghost'}));}article.append(nav);main.replaceChildren(article);}
function showPhoto(){const p=photoList[photoIndex];$('largePhoto').src=p.url;$('largePhoto').alt=p.caption||`Photo ${photoIndex+1}`;$('photoCredit').replaceChildren(h('p',{},p.caption||''),h('p',{},`${photoIndex+1} / ${photoList.length} · ${p.creator||''}${p.license?` · ${p.license}`:''}`),p.sourceUrl?external('Image source',p.sourceUrl):null,p.licenseUrl?[' · ',external('License',p.licenseUrl)]:null);$('previousPhoto').disabled=photoList.length<2;$('nextPhoto').disabled=photoList.length<2;}
function stepPhoto(n){photoIndex=(photoIndex+n+photoList.length)%photoList.length;showPhoto();}
$('previousPhoto').onclick=()=>stepPhoto(-1);$('nextPhoto').onclick=()=>stepPhoto(1);$('closePhoto').onclick=()=>$('photoDialog').close();
let touchStart; $('photoDialog').addEventListener('touchstart',e=>{touchStart={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};},{passive:true});$('photoDialog').addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)stepPhoto(dx>0?-1:1);touchStart=null;},{passive:true});document.addEventListener('keydown',e=>{if($('photoDialog').open && ['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();stepPhoto(e.key==='ArrowLeft'?-1:1);}});
function renderSettings(){const theme=document.documentElement.dataset.theme||'dark';const appearance=h('section',{class:'panel'},h('h2',{},'Appearance'),h('p',{},'Choose the view that feels best wherever you are.'),h('div',{class:'toolbar'},...['light','dark'].map(t=>h('button',{type:'button',class:`button ${t===theme?'primary':''}`,'aria-pressed':t===theme,onclick:()=>{applyTheme(t);renderSettings();}},t==='light'?'Light':'Dark'))));const account=h('section',{class:'panel'},h('h2',{},'Account'),h('p',{},state.user.email||'Signed in with Google'),h('p',{class:'small',id:'syncStatus'},state.status),button('Sign out',signOut));const downloads=h('section',{class:'panel full'},h('h2',{},'Offline downloads'),h('p',{},'Downloads are saved on this device. Removing one keeps the trip in your shared collection.'),h('div',{id:'downloadList'}));const imports=h('section',{class:'panel'},h('h2',{},'Import a guidebook'),h('p',{},'Use a Glauco trip file prepared from the Lambus Daily Plan.'),button('Import trips',openImport,true),link('Template & instructions','setup.html#import',{class:'setup-link'}));const sync=h('section',{class:'panel'},h('h2',{},'About Glauco'),h('p',{},'Your shared, read-only travel guide.'),h('p',{class:'small'},'Version 1.0.1 · Built for the places you visit.'),link('Setup guide','setup.html'),h('div',{id:'conflicts'}));main.replaceChildren(titleBlock('Settings','Make yourself at home.'),h('div',{class:'settings-grid'},appearance,account,downloads,imports,sync));patchDownloads();patchConflicts();}
function patchDownloads(){const list=$('downloadList');if(!list)return;list.replaceChildren();const existing=new Set();for(const d of [...state.downloads.values()].sort((a,b)=>a.name.localeCompare(b.name))){existing.add(d.id);const e=state.entries.get(d.id);list.append(h('div',{class:'download-row'},h('div',{},h('h3',{},d.name),h('p',{},`${sizeLabel(d.bytes)} · ${d.imageCount} images · Saved ${dateLabel(new Date(d.downloadedAt).toISOString().slice(0,10))}`),e&&e.revision!==d.revision?h('p',{class:'status warning'},'A newer guide is available'):null),h('div',{class:'toolbar'},e?button('Update',()=>startDownload(d.id,true)):null,button('Remove',()=>removeDownload(d.id)))));}
 for(const [id,running] of downloadsRunning){list.append(h('div',{class:'progress-wrap',id:`progress-${id}`},h('div',{class:'progress-head'},h('p',{},state.entries.get(id)?.meta.name||'Trip'),button('Cancel',()=>running.controller.abort())),h('p',{class:'small',id:`progressText-${id}`},'Preparing…'),h('progress',{id:`progressBar-${id}`,max:1,value:0})));if(running.progress)showProgress(id,running.progress);}
 if(!existing.size&&!downloadsRunning.size)list.append(h('p',{class:'small'},'No trips downloaded yet. Use Download on a trip to save it here.'));}
function patchConflicts(){const box=$('conflicts');if(!box)return;box.replaceChildren(...[...state.outbox.values()].filter(o=>o.conflict).map(o=>h('div',{class:'conflict-row'},h('h3',{},'Sync conflict'),h('p',{},`${state.entries.get(o.id)?.meta.name||'A trip'} was changed on another device. Your imported file remains the source copy.`),button('Use synced version',()=>resolveConflict(o)))));}
async function persist(entry){const pending=state.outbox.has(entry.id);await store.put('trips',{...entry,trip:pending?entry.trip:null});}
async function archive(entry){entry=state.entries.get(entry.id);if(!entry)return;if(state.outbox.has(entry.id)){notice('Sync this trip before changing its archive status.');return;}const previousRevision=entry.archiveRevision,previousArchived=entry.archived;entry.archived=!entry.archived;entry.archiveRevision=uid();const op={id:entry.id,type:'archive',expectedRevision:entry.revision,expectedArchiveRevision:previousRevision,previousArchived};state.outbox.set(entry.id,op);try{await store.change([{store:'trips',value:{...entry,trip:null}},{store:'outbox',value:op}]);patchTrips();notice(entry.archived?'Trip archived.':'Trip restored.');flush();}catch(error){state.outbox.delete(entry.id);entry.archived=previousArchived;entry.archiveRevision=previousRevision;notice('Could not save this change on your device.');}}
function openImport(){if(!state.user)return;importTrips=[];$('importPreview').replaceChildren();$('importError').textContent='';$('importFile').value='';$('confirmImport').disabled=true;showDialog($('importDialog'));}
$('importFile').addEventListener('change',async()=>{const file=$('importFile').files[0];$('confirmImport').disabled=true;$('importPreview').replaceChildren();$('importError').textContent='';importTrips=[];if(!file)return;try{if(file.size>MAX_FILE)throw new Error('The file is larger than 12 MB.');const epoch=state.epoch;const trips=parseImport(await file.text());if(epoch!==state.epoch||!$('importDialog').open)return;importTrips=trips;for(const trip of trips){const matches=[...state.entries.values()].filter(e=>e.id===trip.id||(e.meta.name.toLocaleLowerCase()===trip.name.toLocaleLowerCase()&&e.meta.year===trip.year));const select=h('select',{'data-import-id':trip.id,'aria-label':`Import action for ${trip.name}`},h('option',{value:'new'},matches.length?'Import as a new trip':'Import trip'));for(const e of matches)select.append(h('option',{value:e.id},`Replace ${e.meta.name}${e.archived?' (archived)':''}`));$('importPreview').append(h('div',{class:'import-row'},h('h3',{},trip.name),h('p',{},`${dateLabel(trip.startDate)} – ${dateLabel(trip.endDate)} · ${trip.days.length} days · ${attractions(trip).length} attractions`),select));}$('confirmImport').disabled=false;}catch(error){$('importError').textContent=error.message;}});
$('confirmImport').onclick=async()=>{if(busyImport||!importTrips.length)return;busyImport=true;$('confirmImport').disabled=true;$('importError').textContent='';const epoch=state.epoch;try{const selected=[...$('importPreview').querySelectorAll('select')].map(s=>s.value).filter(v=>v!=='new');if(new Set(selected).size!==selected.length)throw new Error('Choose a different replacement trip for each import.');const operations=[],created=[];
 for(const trip of importTrips){const choice=[...$('importPreview').querySelectorAll('select')].find(s=>s.dataset.importId===trip.id).value;const old=choice==='new'?null:state.entries.get(choice);if(old&&state.outbox.has(old.id))throw new Error('A replacement trip has an unsynced change. Sync it first.');const newId=old?.id||(!state.entries.has(trip.id)?trip.id:uid());const nextTrip={...trip,id:newId};const entry={id:newId,trip:nextTrip,meta:tripMeta(nextTrip),revision:uid(),archiveRevision:uid(),archived:old?.archived||false};const op={id:newId,type:'import',expectedRevision:old?.revision||null};operations.push({store:'trips',value:entry},{store:'outbox',value:op});created.push({entry,op});}
 if(epoch!==state.epoch||!state.user)throw new Error('Sign in again before importing.');await store.change(operations);if(epoch!==state.epoch)return;for(const {entry,op} of created){state.entries.set(entry.id,entry);state.outbox.set(entry.id,op);}busyImport=false;$('importDialog').close('imported');notice(`${created.length===1?'Trip':'Trips'} imported${navigator.onLine?'.':' and saved locally. Sync will resume online.'}`);location.hash='/trips';renderTrips();flush();
 }catch(error){$('importError').textContent=error.message;}finally{busyImport=false;$('confirmImport').disabled=false;}};
async function startDownload(id,force=false){const entry=state.entries.get(id);if(!entry)return;if(downloadsRunning.has(id)){location.hash='/settings';renderSettings();return;}if(state.downloads.has(id)&&!force){location.hash='/settings';renderSettings();return;}if(!navigator.onLine){notice('Connect to the internet to download this trip.');return;}const controller=new AbortController(),epoch=state.epoch;downloadsRunning.set(id,{controller});location.hash='/settings';renderSettings();try{const trip=await ensureTrip(entry);controller.signal.throwIfAborted();if(epoch!==state.epoch)throw new Error('CANCELLED');const d=await downloadTrip({...entry,trip},p=>{const running=downloadsRunning.get(id);if(running)running.progress=p;showProgress(id,p);},controller.signal);if(epoch!==state.epoch){await deleteDownload(id);return;}state.downloads.set(id,d);await navigator.storage?.persist?.();notice('Trip ready for offline reading.');}catch(error){if(epoch===state.epoch)notice(controller.signal.aborted?'Download cancelled.':error.message);}finally{downloadsRunning.delete(id);if(route().kind==='settings')patchDownloads();}}
function showProgress(id,p){const bar=$(`progressBar-${id}`),label=$(`progressText-${id}`);if(bar){bar.max=Math.max(1,p.total);bar.value=p.done?bar.max:p.completed;}if(label)label.textContent=`${p.completed} of ${p.total} images · ${sizeLabel(p.bytes)}`;}
async function removeDownload(id){if(downloadsRunning.has(id)){notice('Cancel or finish the download before removing it.');return;}if(!await ask('Remove this download?','The local guide and downloaded images will be removed. The shared trip remains available online.'))return;try{await deleteDownload(id);state.downloads.delete(id);const e=state.entries.get(id);if(e&&!state.outbox.has(id))e.trip=null;patchDownloads();notice('Download removed from this device.');}catch{notice('Could not remove the download. Try again.');}}
async function flush(){if(syncJob){syncAgain=true;return syncJob;}if(!state.user||!navigator.onLine)return;const epoch=state.epoch;syncJob=(async()=>{for(const op of [...state.outbox.values()]){if(epoch!==state.epoch||!navigator.onLine)return;if(op.conflict)continue;const e=state.entries.get(op.id);if(!e)continue;status('Syncing…');try{const cancelled=()=>epoch!==state.epoch||!state.user;if(op.type==='import')await cloud.saveImport(e,op.expectedRevision,cancelled);else await cloud.saveArchive(e,op.expectedRevision,op.expectedArchiveRevision,cancelled);if(cancelled())return;if(state.outbox.get(op.id)!==op)continue;await store.remove('outbox',op.id);if(cancelled())return;state.outbox.delete(op.id);await persist(e);patchTrips();}catch(error){if(epoch!==state.epoch)return;if(error.message==='CONFLICT'){op.conflict=true;await store.put('outbox',op);notice('A trip changed on another device. Review the conflict in Settings.');patchConflicts();}else{status('Sync paused · changes saved locally');return;}}}status(state.outbox.size?'Changes need attention':'Synced');})().finally(()=>{syncJob=null;if(syncAgain){syncAgain=false;setTimeout(flush,0);}});return syncJob;}
async function resolveConflict(op){if(!navigator.onLine)return notice('Connect to resolve this conflict.');if(!await ask('Use the synced version?','This replaces the unsynced local change. You can re-import your original file later.'))return;try{const meta=await cloud.remoteMeta(op.id);await store.remove('outbox',op.id);state.outbox.delete(op.id);if(meta){const entry={id:meta.id,meta,revision:meta.revision,archiveRevision:meta.archiveRevision,archived:meta.archived,trip:null};state.entries.set(entry.id,entry);await persist(entry);}else{state.entries.delete(op.id);await store.remove('trips',op.id);}patchConflicts();patchTrips();status(state.outbox.size?'Changes need attention':'Synced');}catch(error){notice('Could not load the synced version. Try again.');}}
async function receive(metas){if(!state.user)return;const epoch=state.epoch;for(const rawMeta of metas){try{const meta=normalizeMeta(rawMeta);const id=text(meta.id,100,'Trip ID',true);if(!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,99}$/.test(id)||!Array.isArray(meta.days)||typeof meta.name!=='string'||typeof meta.revision!=='string')continue;const old=state.entries.get(id);if(state.outbox.has(id))continue;const changed=old?.revision!==meta.revision;const entry={id,meta,revision:meta.revision,archiveRevision:meta.archiveRevision,archived:meta.archived===true,trip:changed?null:old?.trip||null};state.entries.set(id,entry);await persist(entry);if(epoch!==state.epoch)return;if(route().id===id&&changed&&route().kind!=='attraction'&&!document.querySelector('dialog[open]')&&!$('tripSearch')?.value){renderRoute();}}catch{status('A synced trip could not be read.');}}
 state.loaded=true;if(route().kind==='trips'||!route().kind)patchTrips();if(!state.outbox.size)status(navigator.onLine?'Synced':'Offline');}
async function authChanged(user){const epoch=++state.epoch;unsubscribe?.();unsubscribe=null;if(!cloud.authorized(user)){state.user=null;downloadsRunning.forEach(r=>r.controller.abort());state.entries.clear();state.downloads.clear();state.outbox.clear();await store.clearPrivate();if(user){status('This Google account is not authorized for Glauco.');await cloud.logout();}else if(!state.status.includes('not authorized'))status('Sign in to open your guidebooks');gate();return;}
 state.user=user;status(navigator.onLine?'Syncing…':'Offline · saved guidebooks');try{const [entries,downloads,outbox]=await Promise.all([store.all('trips'),store.all('downloads'),store.all('outbox')]);if(epoch!==state.epoch)return;state.entries=new Map(entries.map(e=>[e.id,e]));state.downloads=new Map(downloads.map(e=>[e.id,e]));state.outbox=new Map(outbox.map(e=>[e.id,e]));state.loaded=true;renderRoute();await removeOrphans();unsubscribe=cloud.listen(receive,error=>{status(`Sync unavailable (${error.code||'connection error'})`);notice('Your downloaded trips are still available. Check the Firebase rules and connection.');});flush();}catch{status('Browser storage unavailable');notice('Glauco needs browser storage to save imports and offline trips.');renderRoute();}}
async function signOut(){if(!await ask('Sign out?','Downloaded trips and private local data will be removed from this device.'+(state.outbox.size?' Unsynced changes will be discarded.':'')))return;const epoch=++state.epoch;unsubscribe?.();unsubscribe=null;state.user=null;downloadsRunning.forEach(r=>r.controller.abort());document.querySelectorAll('dialog[open]').forEach(d=>d.close());state.entries.clear();state.downloads.clear();state.outbox.clear();status('Signing out…');gate();try{await cloud.logout();}catch{notice('Google sign-out needs a retry. Local guidebooks have been cleared.');}await store.clearPrivate();if(epoch<=state.epoch){status('Sign in to open your guidebooks');gate();}}
function applyTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem('glauco-theme',theme);}catch{}document.querySelector('meta[name=theme-color]').content=theme==='light'?'#f5f7f6':'#0a1e20';}
try{applyTheme(localStorage.getItem('glauco-theme')||'dark');}catch{applyTheme('dark');}
window.addEventListener('online',()=>{status('Reconnecting…');if(state.user){cloud.setNetwork(true).then(flush).catch(()=>status('Sync unavailable'));}checkRelease();});window.addEventListener('offline',()=>{status('Offline · saved guidebooks');if(state.user)cloud.setNetwork(false).catch(()=>{});});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;let dismissed=false;try{dismissed=localStorage.getItem('glauco-install-dismissed')==='1';}catch{}if(!dismissed)$('installBanner').classList.remove('hidden');});$('installApp').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('installBanner').classList.add('hidden');};$('dismissInstall').onclick=()=>{$('installBanner').classList.add('hidden');try{localStorage.setItem('glauco-install-dismissed','1');}catch{}};
let registration,newRelease=false;const RELEASE='1.0.1';
async function checkRelease(){if(!navigator.onLine)return;try{const response=await fetch(`release.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)return;const release=await response.json();if(release.version!==RELEASE){newRelease=true;await registration?.update();$('releaseBanner').classList.remove('hidden');}}catch{}}
$('updateApp').onclick=async()=>{if(document.querySelector('dialog[open]')||downloadsRunning.size||busyImport){notice('Finish the open dialog or download before updating.');return;}if(state.outbox.size&&navigator.onLine)await flush();if(state.outbox.size){notice('Sync pending changes before updating.');return;}if(registration?.waiting)registration.waiting.postMessage({type:'ACTIVATE'});else if(newRelease)location.reload();};
if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').then(r=>{registration=r;if(r.waiting){newRelease=true;$('releaseBanner').classList.remove('hidden');}r.addEventListener('updatefound',()=>{const worker=r.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){newRelease=true;$('releaseBanner').classList.remove('hidden');}});});}).catch(()=>notice('Offline app support could not start. Use HTTPS and allow site storage.'));let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloading&&newRelease){reloading=true;location.reload();}});}
setTimeout(checkRelease,1800);setInterval(()=>{if(state.user&&navigator.onLine&&state.outbox.size)flush();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){checkRelease();if(state.user&&navigator.onLine)flush();}});
routeKey=location.hash||'#/trips';updateNav();
if(cloud.configured()){status('Checking your account…');gate();try{cloud.startAuth(authChanged);}catch(error){status(`Firebase could not start (${error.code||'configuration error'})`);gate();}}
else{status('Firebase setup required');gate();}
