// Deploy this file as the travel-guide Cloudflare Worker. Store secrets with Wrangler or the Cloudflare dashboard.
const json=(body,status=200,origin='')=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}});
const safeId=value=>String(value||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,100);
const hex=buffer=>[...new Uint8Array(buffer)].map(value=>value.toString(16).padStart(2,'0')).join('');
async function signature(params,secret){const text=Object.entries(params).sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>`${key}=${value}`).join('&')+secret;return hex(await crypto.subtle.digest('SHA-1',new TextEncoder().encode(text)));}
async function member(request,env){const token=(request.headers.get('Authorization')||'').replace(/^Bearer\s+/,'');if(!token)return false;const response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${env.FIREBASE_API_KEY}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:token})});if(!response.ok)return false;const data=await response.json(),allowed=new Set(String(env.ALLOWED_UIDS||'').split(',').map(value=>value.trim()).filter(Boolean));return allowed.has(data.users?.[0]?.localId);}
const delivery=(cloud,publicId,transform)=>`https://res.cloudinary.com/${cloud}/image/upload/${transform}/${publicId.split('/').map(encodeURIComponent).join('/')}`;
export default {async fetch(request,env){
 const rawOrigin=request.headers.get('Origin')||'',origin=rawOrigin.replace(/\/+$/,''),allowedOrigin=String(env.ALLOWED_ORIGIN||'https://snowsences.github.io').replace(/\/+$/,''),isAllowed=!rawOrigin||origin===allowedOrigin,responseOrigin=rawOrigin||allowedOrigin;
 if(request.method==='OPTIONS'){if(!isAllowed)return new Response(null,{status:403,headers:{'Access-Control-Allow-Origin':allowedOrigin,'Vary':'Origin'}});return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':responseOrigin,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':request.headers.get('Access-Control-Request-Headers')||'Authorization, Content-Type','Access-Control-Max-Age':'86400','Vary':'Origin'}});}
 if(!isAllowed)return json({error:'Origin not allowed.'},403,allowedOrigin);if(request.method!=='POST'||!await member(request,env))return json({error:'Not authorized.'},401,responseOrigin);
 const cloudName=String(env.CLOUDINARY_CLOUD_NAME||'').trim(),apiKey=String(env.CLOUDINARY_API_KEY||'').trim(),apiSecret=String(env.CLOUDINARY_API_SECRET||'').trim();if(!cloudName||!apiKey||!apiSecret){console.error('One or more Cloudinary Worker variables are missing.');return json({error:'Cloudinary Worker configuration is incomplete.'},500,responseOrigin);}
 const path=new URL(request.url).pathname.replace(/^\/+|\/+$/g,'');
 if(path==='upload'){
  const data=await request.formData(),file=data.get('file'),tripId=safeId(data.get('tripId')),attractionId=safeId(data.get('attractionId'));if(!(file instanceof File)||!file.type.startsWith('image/')||file.size>10*1024*1024||!tripId||!attractionId)return json({error:'Invalid image upload.'},400,responseOrigin);
  const timestamp=Math.floor(Date.now()/1000),folder=`glauco/${tripId}/${attractionId}`,params={folder,timestamp},signed=await signature(params,apiSecret),body=new FormData();body.append('file',file);body.append('folder',folder);body.append('timestamp',String(timestamp));body.append('api_key',apiKey);body.append('signature',signed);
  const response=await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`,{method:'POST',body}),result=await response.json().catch(()=>({}));if(!response.ok){const message=result?.error?.message||`Cloudinary returned HTTP ${response.status}.`;console.error('Cloudinary upload failed:',response.status,message);return json({error:`Cloudinary: ${message}`},502,responseOrigin);}return json({publicId:result.public_id,url:delivery(cloudName,result.public_id,'f_auto,q_auto,w_2400,c_limit'),thumbnailUrl:delivery(cloudName,result.public_id,'f_auto,q_auto,w_640,c_limit')},200,responseOrigin);
 }
 if(path==='destroy'){
  const data=await request.json().catch(()=>({})),ids=Array.isArray(data.publicIds)?data.publicIds.filter(id=>typeof id==='string'&&id.startsWith('glauco/')).slice(0,12):[];for(const public_id of ids){const timestamp=Math.floor(Date.now()/1000),params={public_id,timestamp},signed=await signature(params,apiSecret),body=new URLSearchParams({...params,timestamp:String(timestamp),api_key:apiKey,signature:signed});await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/destroy`,{method:'POST',body});}return json({success:true},200,responseOrigin);
 }
 return json({error:'Not found.'},404,responseOrigin);
}};
